const DATA = {
    especies: [
        // --- Playable (PHB 2024 + Favorites) ---
        "Human", "Elf", "Dwarf", "Halfling", "Tiefling", 
        "Dragonborn", "Gnome", "Orc", "Goliath", "Aasimar",
        "Warforged", "Tortle", "Leonin", "Aarakocra", "Genasi", "Loxodon",
        // --- Extra Humanoids ---
        "Goblin", "Kobold", "Tabaxi", "Kenku", "Githyanki"
    ],
    
    nombres: {
        // --- Core Playables ---
        "Human": [
            "Alaric", "Elara", "Garrick", "Vera", "Kaelen", "Rowan", "Mina", "Osric", "Soren", "Talia",
            "Benedict", "Cassandra", "Darian", "Elowen", "Falk", "Gemma", "Harlan", "Iris", "Jovan", "Kira",
            "Leif", "Mira", "Nolan", "Ophelia", "Pike", "Quentin", "Runa", "Silas", "Thea", "Valerius", 
            "Adelaide", "Balthazar", "Cillian", "Daphne", "Eamon", "Freya", "Gideon", "Hester", "Isidore", "Jocelyn",
            "Kael", "Liora", "Maddock", "Nyssa", "Orion", "Phineas", "Quintessa", "Roderick", "Saskia", "Tobias",
            "Ursula", "Valen", "Winifred", "Xavier", "Yvaine", "Zephyr", "Aldous", "Beatrix", "Cyprian", "Dorothea",
            "Evander", "Florence", "Gregory", "Hilda", "Ignatius", "Julian", "Kassandra", "Lucius", "Maude", "Nathaniel",
            "Octavia", "Percival", "Quinn", "Rosalind", "Sebastian", "Tatiana", "Ulysses", "Victoria", "Wyatt", "Zoraida"
        ],
        "Elf": [
            "Thaelan", "Faenora", "Kyriel", "Sariel", "Elowen", "Meryn", "Valerius", "Iandir", "Arannis", "Lia",
            "Adran", "Aelar", "Aramil", "Arariel", "Enna", "Felosial", "Ielenia", "Keyleth", "Leshanna", "Mialee",
            "Naivara", "Quelenna", "Sariel", "Shanairra", "Theirastra", "Thia", "Vadania", "Valanthe", "Xanaphia", "Zinakas"
        ],
        "Dwarf": [
            "Brundor", "Thorina", "Gimli", "Dagna", "Hogar", "Kilda", "Ulfgar", "Bardel", "Orsik", "Vistra",
            "Adrik", "Alberich", "Baern", "Barendd", "Brottor", "Dain", "Darrak", "Delg", "Eberk", "Einkil",
            "Fargrim", "Flint", "Gardain", "Harbek", "Kildrak", "Morgran", "Rurik", "Taklinn", "Thoradin", "Tordek"
        ],
        "Halfling": [
            "Bilbo", "Rosie", "Pippin", "Tilly", "Finnan", "Lidda", "Merric", "Cora", "Reed", "Paela",
            "Alton", "Ander", "Cade", "Corrin", "Eldon", "Garret", "Lyle", "Milo", "Osborne", "Roscoe",
            "Wellby", "Andry", "Bree", "Callie", "Chenna", "Euphemia", "Gillian", "Kithri", "Lavinia", "Nedda"
        ],
        "Tiefling": [
            "Curse", "Hope", "Ash", "Rigor", "Malice", "Affection", "Revenge", "Gluttony", "Creed", "Artistry",
            "Abadón", "Akmenos", "Amnon", "Barakas", "Damakos", "Ekemon", "Iados", "Kairon", "Leucis", "Melech",
            "Mordai", "Morthos", "Pelaios", "Skamos", "Therai", "Anakis", "Bryseis", "Criella", "Damaia", "Ea"
        ],
        "Dragonborn": [
            "Arjhan", "Balasar", "Donaar", "Ghesh", "Kriv", "Medrash", "Nadarr", "Patrin", "Rhogar", "Sora",
            "Pandjed", "Bharash", "Bivrua", "Donaar", "Ghesh", "Heskan", "Kriv", "Medrash", "Mehen", "Nadarr",
            "Patrin", "Rhogar", "Shamash", "Shedinn", "Tarhun", "Torinn", "Akra", "Biri", "Daar", "Farideh"
        ],
        "Gnome": [
            "Boddynock", "Dimble", "Fonkin", "Gimble", "Namfoodle", "Roondar", "Zook", "Lilli", "Pip", "Nissa",
            "Alston", "Alvyn", "Boddynock", "Brocc", "Burgell", "Dimble", "Eldon", "Erky", "Fonkin", "Frug",
            "Gerbo", "Gimble", "Glim", "Jebeddo", "Kellen", "Namfoodle", "Orryn", "Roondar", "Seebo", "Sindri"
        ],
        "Orc": [
            "Brugh", "Drog", "Garak", "Korg", "Mug", "Raza", "Thokk", "Varg", "Lurka", "Urzul",
            "Dench", "Feng", "Gell", "Henk", "Holg", "Imsh", "Keth", "Krusk", "Mhurren", "Ront",
            "Shump", "Thokk", "Baggi", "Emen", "Engong", "Kansif", "Myev", "Neega", "Ovak", "Ownka"
        ],
        "Goliath": [
            "Aukan", "Ehalu", "Gae-Al", "Kavak", "Lo-Kag", "Maveith", "Thalai", "Uthal", "Vakora", "Keothi",
            "Anakalathai", "Elanithino", "Gathakanathi", "Kalagiano", "Kolae-Gileana", "Oglakanu", "Thuliaga", "Thunukalathi", "Vaquano", "Vunavue-Maveith",
            "Aguilero", "Bearkiller", "Dawnwatcher", "Fearless", "Flintfinder", "Horncarver", "Mountainclimber", "Riverjumper", "Skywatcher", "Steadyhand"
        ],
        "Aasimar": [
            "Aasir", "Balthazar", "Casiel", "Dariel", "Ephraim", "Gabriel", "Hadriel", "Ithuriel", "Remiel", "Zariel",
            "Uriel", "Sariel", "Raziel", "Ramiel", "Ophaniel", "Muriel", "Jophiel", "Israfil", "Haniel", "Dumah",
            "Daniel", "Castiel", "Barachiel", "Azrael", "Aniel", "Amitiel", "Adriel", "Abasdarhon", "Abaddon", "Zaphkiel"
        ],
        "Warforged": [
            "Anvil", "Hammer", "Seven", "Sentinel", "Bastion", "Edge", "Rust", "Bolt", "Unit 42", "Zero",
            "Steel", "Bulwark", "Cannon", "Dagger", "Axle", "Forge", "Granite", "Iron", "Joint", "Kilowatt",
            "Spear", "Notch", "Nickel", "Onyx", "Lead", "Keel", "Radar", "Saw", "Tower", "Beam"
        ],
        "Tortle": [
            "Kome", "Mudlow", "Platón", "Tortu", "Grum", "Oog", "Shellon", "Pok", "Quill", "Gourd",
            "Burt", "Clyde", "Dung", "Ebb", "Flo", "Gully", "Hunk", "Itch", "Jabb", "Krug",
            "Lump", "Muck", "Nog", "Oat", "Puff", "Quah", "Rudge", "Snout", "Tug", "Urth"
        ],
        "Leonin": [
            "Ajani", "Hmar", "Kytheon", "Makos", "Pyxis", "Rago", "Tethos", "Zora", "Lio", "Mufar",
            "Atreos", "Brutus", "Cástor", "Dymas", "Erebo", "Fobos", "Gorgas", "Helios", "Ícaro", "Jano",
            "Kórax", "Licos", "Midas", "Nereo", "Orión", "Palas", "Quirón", "Rómulo", "Silas", "Tifón"
        ],
        "Aarakocra": [
            "Aera", "Fierka", "Oerk", "Qiik", "Rikth", "Zark", "Klee", "Praw", "Gyr", "Akra",
            "Chirr", "Dakk", "Eek", "Fffr", "Grrr", "Hrrr", "Iikk", "Jrrr", "Krrr", "Lrrr",
            "Mrrr", "Nrrr", "Orrr", "Prrr", "Qrrr", "Rrrr", "Srrr", "Trrr", "Urrr", "Vrrr"
        ],
        "Genasi": [
            "Ember", "Gust", "Tide", "Flint", "Zephyr", "Magma", "Dew", "Quartz", "Ignis", "Aqua",
            "Smoke", "Sirocco", "Cinder", "Frost", "Silt", "Pebble", "Cloud", "Torrent", "Ash", "Steam",
            "Horizon", "Abyss", "Chasm", "Summit", "Wasteland", "Jungle", "Dune", "Coral", "Sulfur", "Amber"
        ],
        "Loxodon": [
            "Bayu", "Ganesha", "Illo", "Luma", "Thrum", "Vanu", "Oman", "Pagu", "Kandu", "Boro",
            "Aru", "Bava", "Cavun", "Duma", "Eshat", "Fandun", "Ganesh", "Huna", "Indu", "Jandun",
            "Kanu", "Luma", "Mava", "Nandu", "Onu", "Pava", "Ranu", "Savu", "Thrum", "Vanu"
        ],

        "Goblin": [
            "Droop", "Snot", "Griz", "Punt", "Vark", "Zix", "Splug", "Klarg", "Boogle", "Dobby",
            "Gazza", "Jib", "Knox", "Ludo", "Mog", "Nix", "Ozzy", "Pox", "Ratty", "Skab",
            "Titch", "Vex", "Wiz", "Yappy", "Zog", "Bite", "Chomp", "Gnash", "Snap", "Snarl"
        ],
        "Kobold": [
            "Meepo", "Ikk", "Sniv", "Kipe", "Zat", "Grak", "Pook", "Vix", "Kura", "Saka",
            "Daks", "Eek", "Fik", "Gark", "Heks", "Ip", "Jaks", "Kip", "Lek", "Mek",
            "Neks", "Ok", "Pek", "Qak", "Reks", "Sik", "Tik", "Uks", "Vik", "Zek"
        ],
        "Tabaxi": [
            "River in the Night", "Tree Shadow", "Five Mirrors", "Wind Feather", "Snow Cat", "Distant Cloud",
            "Cricket Song", "Starlight", "Thunder Step", "Storm Eye", "Iron Claw", "Whisper of Leaves",
            "Lone Rock", "Deep Valley", "Snowy Summit", "Morning Dew", "Eternal Flame", "North Wind",
            "Hot Sand", "Dark Forest", "Crystal Sea", "Blood Moon", "Winter Sun", "Long Road",
            "Silver Bridge", "Ivory Tower", "Deep Cave", "Swift River", "Green Meadow", "Blue Sky"
        ],
        "Kenku": [
            "Caw", "Clanc", "Echo", "Whisper", "Rust", "Whistle", "Snap", "Thud", "Creak", "Buzz",
            "Whistle", "Bell", "Hammerblow", "Drip", "Roar", "Screech", "Explosion", "Wind", "Thunder", "Rain",
            "Fire", "Crystal", "Paper", "Chain", "Door", "Footsteps", "Laughter", "Crying", "Scream", "Song"
        ],
        "Githyanki": [
            "Arrak", "Gaath", "Hrath", "K'lyss", "Madar", "R'ayth", "Vlaakith", "Zar-Ek", "Xam", "Yuan",
            "Zal", "Arak", "Baal", "Caar", "Daar", "Eer", "Faar", "Gaar", "Haar", "Iiar",
            "Jaar", "Kaar", "Laar", "Maar", "Naar", "Oaar", "Paar", "Qaar", "Raar", "Saar"
        ]
    },



"Nombres_Globales": [
    "Abraxas", "Adonais", "Aglon", "Akra", "Amara", "Anathel", "Antua", "Argus", "Arlow", "Asha", 
    "Azriel", "Bael", "Barda", "Belial", "Beryn", "Blain", "Boaz", "Borg", "Brant", "Bryn", 
    "Caelum", "Calix", "Candra", "Cato", "Cax", "Celes", "Chard", "Ciro", "Colm", "Corvus", 
    "Dael", "Dagon", "Dante", "Dara", "Dax", "Demitri", "Doran", "Draven", "Duer", "Duma", 
    "Egan", "Eira", "Elian", "Elowan", "Emet", "Enzo", "Eris", "Esme", "Ezra", "Fael", 
    "Fane", "Faust", "Fenyx", "Fionn", "Flint", "Flynn", "Galan", "Gant", "Garek", "Gavin", 
    "Gora", "Grendel", "Hadar", "Halia", "Harko", "Haze", "Hestia", "Hollis", "Hyram", "Idris", 
    "Igon", "Ilara", "Inaya", "Indra", "Iori", "Iskan", "Iva", "Izar", "Jace", "Jada", 
    "Jarek", "Jarl", "Jaya", "Jedd", "Jinx", "Joren", "Kael", "Kai", "Kaly", "Kano", 
    "Kazi", "Kean", "Kento", "Kiba", "Koda", "Kaelen", "Lael", "Lark", "Lazar", "Leda", 
    "Lian", "Lobo", "Loke", "Loran", "Lumi", "Mace", "Malik", "Maren", "Maro", "Mura", 
    "Nadir", "Nala", "Nao", "Narek", "Nero", "Niles", "Nix", "Nova", "Nox", "Nyx", 
    "Odin", "Olam", "Onyx", "Oren", "Orion", "Orla", "Osias", "Otho", "Oz", "Paxon", 
    "Phaedra", "Pyre", "Qad", "Quon", "Radek", "Raiden", "Rave", "Raya", "Razo", "Remi", 
    "Rhea", "Rico", "Rogue", "Runa", "Ryker", "Saba", "Saffron", "Saka", "Saren", "Sayer", 
    "Seth", "Shade", "Sira", "Sloane", "Soren", "Stark", "Sya", "Talon", "Tarek", "Thane"
],

profesiones: {
    town: {
        poor: [
            "Day laborer",
            "Turnip farmer",
            "Sheep herder",
            "Lumberjack",
            "Stablehand",
            "River fisher",
            "Trapper",
            "Honey gatherer",
            "Peat gatherer",
            "Charcoal burner",
            "Reaper",
            "Pig breeder",
            "Thatcher",
            "Firewood seller",
            "Animal birth assistant (livestock)",
            "Barn keeper",
            "Weeder",
            "Axeman",
            "Night field watchman",
            "Herb gatherer",
            "Rural tavern helper",
            "River laundress",
            "Goose breeder",
            "Peat cutter",
            "Ditch digger",
            "Shearer",
            "Grain hauler",
            "Gleaner",
            "Mill hand",
            "Eel fisher",
            "Bale loader",
            "Ox driver",
            "Stable cleaner",
            "Fodder seller",

            // NEW
            "Wet firewood gatherer",
            "Root digger",
            "Goat keeper",
            "Nettle gatherer",
            "Other people's pig minder",
            "Harvest hand",
            "Mule drover",
            "Water carrier",
            "Manure collector",
            "Village square sweeper",
            "Fence mender",
            "Hand thresher",
            "Wild apple gatherer",
            "Chicken keeper",
            "Net mender",
            "Bark peeler",
            "Transhumant shepherd",
            "Mushroom forager",
            "Common-fields guard",
            "Brush clearer",
            "Log loader",
            "Flax gatherer",
            "Farrier's helper",
            "Vineyard day laborer",
            "Peasant babysitter",
            "Plowing hand",
            "Nut gatherer",
            "Sick-sheep keeper",
            "Irrigation ditch cleaner",
            "Beehive keeper"
            ],
        middle: [
            "Miller",
            "Farrier",
            "Tanner",
            "Wool weaver",
            "Stonecutter",
            "Candle maker",
            "Rural brewer",
            "Cooper",
            "Well digger",
            "Salt worker",
            "Muleteer",
            "Basket weaver",
            "Grain miller",
            "Ox trainer",
            "Beekeeper",
            "Artisan cheesemaker",
            "Broom maker",
            "Village furrier",
            "Plow maker",
            "Traveling tinker",
            "Cattle herder",
            "Red-clay potter",
            "Truffle hunter",
            "Orchard pruner",
            "Junior ranger",
            "Commune cook",
            "Farm tool mender",
            "Cider presser",
            "Berry picker",
            "Garden keeper",
            "Rope maker",
            "Scythe sharpener",

            // NEW
            "Rural schoolteacher",
            "Commonlands administrator",
            "Village tavernkeeper",
            "Master rural carpenter",
            "Master stonemason",
            "Village healer",
            "Rural veterinarian",
            "Mill owner",
            "Large farm manager",
            "Livestock trader",
            "Forest warden",
            "Rural tax collector",
            "Village scribe",
            "Fair organizer",
            "Master rural baker",
            "Draft-horse breeder",
            "Crop inspector",
            "Small vineyard owner",
            "Cellar manager",
            "Stable manager",
            "Traveling merchant",
            "Master rural blacksmith",
            "Wagon carpenter",
            "Barrel maker",
            "Well-known healer",
            "Master weaver",
            "Communal granary keeper",
            "Field foreman",
            "Seed supplier",
            "Rent collector"
            ]
    },
    city: {
        poor: [
        "Crew boss",
        "Stevedore",
        "Barge rower",
        "Foot messenger",
        "Groom",
        "Barber-surgeon",
        "Traveling dentist",
        "Street juggler",
        "Fire breather",
        "Snake charmer",
        "Town crier",
        "Lamplighter (lights lamps)",
        "Night watchman",
        "Errand runner",
        "Shoeshiner",
        "Sharpener",
        "Flower seller",
        "Pastry seller",
        "Water seller",
        "Crossbow stringer",
        "House painter",
        "Chimney sweep",
        "Sewer rat (cleaner)",
        "Rat catcher",
        "Constable",
        "Gate guard",
        "Jailer",
        "Executioner",
        "Official torturer",
        "Toll collector",
        "Pickpocket",
        "Document forger",
        "Liquor smuggler",
        "Poison dealer",
        "Hitman",
        "Tavern bruiser",
        "Extortionist",
        "Crime-scene cleaner",
        "Street con artist",
        "Professional gambler",
        "Illegal bookie",
        "Boxer",
        "Hustler",
        "Drifter",
        "Professional beggar",
        "Trash collector",
        "Scrap dealer",
        "Sewer treasure hunter",
        "Medium",
        "Fair fortune teller",
        "Card reader",
        "Street alchemist (drugs)",
        "Dream dealer",
        "Uncontracted mercenary",
        "Deserter",
        "River pirate",
        "Grave robber",
        "Organ seller",
        "Swindler",
        "Cardsharp",
        "Knife thrower",
        "Underworld informant",
        "Rooftop rogue",
        "Pack mule",
        "Fence (stolen goods)",
        "Art forger",
        "Slum shaman",
        "Street-corner religious fanatic",
        "Doomsday prophet"
        ],
        middle: [
        "Watchmaker (or gear mechanic)",
        "Apothecary",
        "Bookseller",
        "Glassblower",
        "Knife maker",
        "Locksmith",
        "Fine shoemaker",
        "Hatter",
        "Dyer",
        "Upholsterer",
        "Furniture maker",
        "Bronze worker",
        "Spice merchant",
        "Pastry chef",
        "Charcutier",
        "Map seller",
        "Surveyor",
        "Building contractor",
        "Dock foreman",
        "Ferry captain",
        "Customs officer",
        "Public weigher",
        "Tax assessor",
        "Public scribe",
        "Night tutor",
        "Barber-surgeon",
        "Bathhouse attendant",
        "Theater makeup artist",
        "Comedy actor",
        "Tragedian",
        "Beast tamer",
        "Retired gladiator",
        "Chamber musician",
        "Ballroom dancer",
        "Fencing master",
        "Riding instructor",
        "Librarian of the Great Tower",
        "Archivist",
        "Copyist",
        "Dead-language translator",
        "Urban herbalist",
        "City midwife",
        "Plague doctor",
        "Embalmer",
        "Ruins tour guide",
        "Market watchman",
        "Coach driver",
        "Inn cook",
        "Sommelier",
        "Casino croupier",
        "Club host",
        "Food critic",
        "Correspondent",
        "Mail carrier",
        "Tattoo artist",
        "Wagon mechanic",
        "Sanitation inspector",
        "Fire warden",
        "Book censor",
        "Inquisitor",
        "Master of ceremonies",
        "Tournament herald",
        "Duel referee",
        "Guild spokesperson",
        "Union leader"
        ],
        wealthy: [
        "Royal jeweler",
        "Silk tailor",
        "Luxury furrier",
        "Portrait painter",
        "Marble sculptor",
        "Seal engraver",
        "Spice merchant",
        "Money changer",
        "Usurer",
        "Moneylender",
        "Pawnshop owner",
        "Wine exporter",
        "Silk importer",
        "Antiquities dealer",
        "Luthier (lutes)",
        "Master armorer",
        "Perfumer",
        "Mother-of-pearl inlayer",
        "Silversmith",
        "Goldsmith",
        "Gem merchant",
        "Art dealer",
        "Upscale tavern sommelier",
        "Master chocolatier",
        "Palace baker",
        "Slave trader (or servant broker)",
        "Warhorse dealer",
        "Ship supplier",
        "Architect",
        "Civil engineer",
        "Notary",
        "Defense attorney",
        "Magistrate",
        "Diplomat",
        "Visiting ambassador",
        "Crown spy",
        "District commissioner",
        "Quartermaster",
        "Palace sommelier",
        "Noble house butler",
        "Personal secretary",
        "Guild treasurer",
        "High-class courtesan"
        ]
    }


},

estados: [
        "Hostile",
        "Neutral",
        "Friendly",
    ],

    voces: [
        // --- Volume and Tone ---
        "LOUD volume and DEEP tone (Command/authority voice)",
        "LOW volume and HIGH tone (Shy or childlike voice)",
        "Constant whisper and NEUTRAL tone (As if sharing a secret)",
        "NORMAL volume but VERY DEEP tone (Cavernous/imposing voice)",
        "Constant shouting and HIGH tone (Seems always on the verge of a panic attack)",
        
        // --- Speed and Rhythm ---
        "Speaks VERY FAST and rushed (Anxiety or excess energy)",
        "Speaks VERY SLOW, savoring each syllable (Boredom or extreme old age)",
        "Choppy rhythm, pauses... in... strange places",
        "Speaks without breathing, very long sentences that end in a sigh",
        "Speaks rhythmically, almost as if reciting a poem",

        // --- Texture and Quality (Easy to imitate) ---
        "Nasal (As if their nose were clogged)",
        "Raspy/boozy (As if they needed to clear their throat)",
        "Breathy voice (Exhales a lot while speaking, ethereal/ghostly)",
        "Guttural voice (Speaks from deep in the throat, very resonant)",
        "Tight voice (Speaks with teeth almost closed)",
        "Shrill voice (Forces the throat upward)",
        
        // --- Acting Tics and Mannerisms ---
        "Repeats the last word of every sentence (sentence... sentence)",
        "Overly exaggerates their 'S' sounds (like a snake)",
        "Growls or snorts between sentences",
        "Talks while nervously laughing for no reason",
        "Ends every sentence as if it were a question?",
        "Clicks their tongue before starting to speak",
        "Stutters only when saying proper names",
        "Talks with a full mouth (or pretends to be chewing something)",
        "Clears their throat constantly to interrupt others",
        "Speaks in a monotone, with no emotion at all (robot/zombie)",
        "Syrupy voice, exaggeratedly polite (suspicious)",
        "Talks with a constant yawn, like they’re about to fall asleep",
        "Panting voice, as if they just ran a marathon",
        "Speaks by inhaling air instead of exhaling (startled voice)",

        // --- Technical Combinations ---
        "Low, Deep, and Slow (Calculating villain)",
        "Loud, High, and Fast (Frenetic street vendor)",
        "Normal, Nasal, and Slow (Bored bureaucrat)",
        "Low, Raspy, and Fast (Back-alley conspirator)",
        "Loud, Neutral, and With Pauses (Enlightened prophet)",
        "Whispery, High, and Hissy (Creeping creature)",
        "Deep, Fast, and With a Tight Voice (Stressed soldier)",
        "Normal, Breathy, and Melodic (Distracted noble)"
    ],

    acting: [
        // --- Nervous Tics and Gestures ---
        "Bites their nails compulsively",
        "Constantly scratches their neck, as if a tag were itching",
        "Fidgets with a ring on their finger, taking it off and putting it back on",
        "Blinks excessively fast when questioned",
        "Repeatedly touches their left earlobe",
        "Drums their fingers on any nearby surface",
        "Adjusts their glasses (or an imaginary eyepatch) every few seconds",
        "Moistens their lips constantly with their tongue",
        "Wipes imaginary sweat from their forehead with a dirty handkerchief",
        "Keeps twirling a lock of hair around a finger",

        // --- With Objects (Props) ---
        "Is smoking a pipe that gives off thick bluish smoke",
        "Obsessively cleans a dagger (or a spoon) with a rag",
        "Is drinking very hot tea, loudly blowing on it",
        "Tosses a coin into the air and always catches it",
        "Chews on a licorice root or a piece of leather",
        "Sharpens a pencil or carves a piece of wood with a knife",
        "Flips through a small, wrinkled book, sometimes ignoring the players",
        "Plays with a set of dice in one hand, clacking them together",
        "Is eating something small (nuts, berries) one by one",
        "Cleans their nails with the tip of a pin",

        // --- Posture and Physical State ---
        "Is extremely relaxed, almost sprawled out in their seat",
        "Stands rigid as a board, hands behind their back",
        "Leans forward, invading the players’ personal space",
        "Rocks rhythmically on their heels",
        "Crosses their arms so tightly they look angry",
        "Keeps their head tilted, as if listening to an inner voice",
        "Shrugs constantly while talking",
        "Rubs their hands as if they’re permanently cold",
        "Leans heavily on a cane or on the table",
        "Always looks over their shoulder, as if someone were following them",

        // --- Acting Gestures ---
        "Avoids direct eye contact, always looking at the floor",
        "Stares into the other person’s eyes without blinking",
        "Points with their index finger to emphasize every word",
        "Nods along to everything said, even before it’s finished",
        "Covers their mouth with a hand every time they laugh",
        "Squints, as if they can’t see well up close",
        "Strokes their beard (whether they have one or not) thoughtfully",
        "Moves their hands exaggeratedly, as if conducting an orchestra",
        "Takes their hat off and puts it back on constantly",
        "Looks up at the sky or ceiling for inspiration",

        // --- Visible Mood States ---
        "Seems on the verge of tears, eyes always watery",
        "Has a smug smile etched on their face",
        "Seems distracted, watching flies or things nobody else can see",
        "Acts with extreme urgency, as if running late",
        "Looks like they’re about to fall asleep at any moment",
        "Acts suspicious, covering their mouth so you can’t read their lips",
        "Has an air of superiority, looking down on everyone",
        "Is visibly disgusted by the environment or by the players",
        "Shows an unsettling calm while chaos unfolds around them",
        "Chuckles under their breath at their own thoughts",

        // --- “Effect” Combinations ---
        "Smokes, stares at the horizon, and avoids answering directly",
        "Drinks, nods, and drums the table",
        "Cleans an object, avoids eye contact, and whispers",
        "Scratches their neck, blinks a lot, and talks fast",
        "Rigid posture, hands behind their back, and fixed stare",
        "Relaxed, eats nuts, and smiles smugly",
        "Adjusts their clothes, rubs their hands, and looks at the ceiling",
        "Bites their nails, looks over their shoulder, and stutters"
    ],

fisico: [
        // --- Face and Head (70) ---
        "Vertical scar crossing the left eye", "Broken, poorly healed nose in an S-shape", "Gold front tooth carved with a rune", "Missing an ear (covered by hair)", "Freckles so dense they look like stains", "Braided beard with small bone beads", "Eyebrows so bushy they hide their eyes", "Different-colored eyes (heterochromia)", "Prominent lower jaw with protruding tusks", "Cleft lip partly hidden",
        "Tattoo of a tear under the right eye", "Sunburnt, badly cracked skin", "Hollow cheeks and cadaverous look", "Very pronounced double chin", "Completely shaved, polished head", "Long sideburns that reach the jaw", "Pockmarked face from smallpox or acne scars", "Wears a smoked-glass monocle", "Bulging eyes that always look surprised", "Extremely pointy, red nose",
        "Burn scar covering one whole side of the face", "Unnatural hair color (blue, pink, green)", "Wears a leather eyepatch with a skull design", "Has a third eye tattooed on their forehead", "Snow-white eyelashes", "Unusually large, pointed ears", "Teeth filed to sharp points (shark-like)", "Always has a straw stem in their mouth", "Wears a hairnet with fake pearls", "Has their face painted with white ash",
        "Circular scar on the forehead (cup mark)", "Cheekbones so high and sharp they look like blades", "A forked tongue that shows while speaking", "Has a constant tic in the left eyelid", "Face always smudged with soot", "Bone piercings in their eyebrows", "Pale, almost translucent skin; veins visible", "Round, rosy face like an apple", "Badly applied stage makeup", "Claw scars on the cheek",
        "Perfectly trimmed circle beard", "Has a permanently angry expression", "Eyes half-closed as if it’s always too bright", "Very high, open forehead", "Olive skin with an oily sheen", "Flattened boxer’s nose", "Wears a leather mask that only covers the nose", "Black teeth from chewing some root", "Has a large mole with a long hair", "Plucked eyebrows drawn on with charcoal",
        "Face covered in tribal tattoos", "Wears a thin veil that hides their mouth", "Hair pulled into an extremely tight ponytail", "Big sideburns that connect to the mustache", "Wears wooden false teeth", "Bloodshot eyes from lack of sleep", "A small jewel set into a tooth", "Always has food caught in their beard", "Very freckled around the nose", "Wears earrings made of bird talons",
        "Scar from ear to ear across the neck", "Graying hair only at the temples", "A look that seems to see right through you", "Wears a clean bandage wrapped around their head", "Very asymmetrical face", "Nose with a heavy hoop piercing", "Has suction-cup marks on the neck", "Wears faded blue war paint", "Matted hair with tiny bird nests", "Always has cracked, bleeding lips",

        // --- Body and Build (80) ---
        "Extremely tall and thin (beanpole)", "Short, broad, with shoulders like an ox", "Missing the right arm from the elbow down", "Walks with a pronounced limp in the left leg", "Has a pronounced hunchback", "Disproportionately large hands", "Body covered in very thick body hair", "Hunched posture as if carrying an invisible weight", "Has six fingers on the right hand", "Skin covered in dry scales on the arms",
        "Defined musculature like an athlete", "Beer belly that strains the buttons", "A cleaver scar across the chest", "Wears a rough mechanical (or wooden) arm", "A map tattoo across the entire back", "Very short neck; looks like they don’t have one", "Very narrow waist and broad shoulders", "Body full of recent bruises", "Bow-legged like a rider", "Trembling hands they can’t stop",
        "Wears a leather brace to support their back", "Has a birthmark shaped like a dragon", "Tanned skin with armor tan lines", "Wears a heavy chain tied around the waist", "Very agile body; moves like a cat", "Knuckles calloused and deformed", "Drooping shoulders and chronic exhaustion look", "Wears a necklace of dried ears", "Very soft skin; clearly never did physical labor", "Has whip scars on the back",
        "Missing several toes", "Chest tattooed with a radiant sun", "Very hairy body, even on the shoulders", "Wears a broken shackle on the ankle", "Fragile build; looks like they might break", "Obvious physical strength in a handshake", "Moves very stiffly, almost mechanically", "Carries a backpack that seems heavier than them", "Skin covered in birthmarks", "One shoulder higher than the other",
        "Uses an iron leg prosthesis", "Runic tattoos that glow in the dark", "Body riddled with old arrow wounds", "Hands always stained with ink or paint", "Body smells like fresh flowers", "Has a hand-shaped burn on the arm", "Wears a belt with twenty small pockets", "Wears layers of clothes that make them look bigger", "Has a bouncy walk", "Moves without making the slightest sound",
        "Sweaty body even in winter", "Claw marks on the forearms", "Has a small snake tattoo winding around the neck", "Missing a thumb", "Always wears silk gloves to hide something", "Has perfect military posture", "Body with strange surgical scars", "Has a gem embedded in the navel", "Skin texture like old leather", "Wears a cloak made from many different animal hides",
        "Build of someone who’s been starving a long time", "Has a tattoo of their own name on the arm", "Wears a key on their chest on a gold chain", "Body that seems to give off slight heat", "Painted black fingernails", "Wears a metal corset under their clothes", "Frostbite marks on the hands", "Wears a fishing net as part of their outfit", "Has a short tail (if the species doesn’t)", "Uses a wooden frame to correct posture",
        "Body smells of sulfur and smoke", "Has an arrow tattoo pointing to their head", "Has a bag of salt tied to the knee", "Very flexible body, almost contortionist", "Has a lightning-shaped burn mark", "Wears a small shield strapped to the forearm", "Skin covered in glitter or gold dust", "Has a tic that makes their shoulders jerk", "Wears a crude gas mask hanging from the neck", "Body that seems to vibrate slightly",

        
        // --- Smells and Final Details (75) ---
        "Smells strongly of cinnamon and cloves", "Smells like wet dog and mud", "Smells like dead flowers (funeral-like)", "Smells like rusty iron and blood", "Smells like freshly baked bread", "Smells like sewers and damp", "Smells like very sweet pipe smoke", "Smells like mint and eucalyptus", "Smells like stale sweat and leather", "Smells like overpowering rose perfume",
        "Smells like the sea and salt air", "Smells like incense from an ancient temple", "Smells like stable and manure", "Smells like strong, cheap alcohol", "Smells like gunpowder and sulfur", "Smells like freshly cut wood", "Smells like rotten fish", "Smells like honey and beeswax", "Smells like vinegar and cleaning products", "Smells like basement damp",
        "Is always surrounded by flies", "Has a very cold body temperature to the touch", "Has rectangular pupils (like a goat)", "Has hairy palms", "Their nails change color with their mood", "Has no belly button", "Their shadow seems to move one second late", "Emits a faint buzzing when nervous", "Has bright blue blood", "Has perfect spiral fingerprints",
        "Skin glows slightly in moonlight", "Has two rows of teeth", "Ears twitch when they hear a noise", "Never blinks while speaking", "Voice sounds like two people speaking at once", "Has a very slow pulse (10 beats per minute)", "Tears are black like ink", "Sweat smells like vanilla", "Has a burn mark that looks like a star map", "Knees crack loudly when walking",
        "Has a tattoo that changes location every day", "Eyes glow faintly in the dark", "Breath is always icy, even in summer", "Has a small rabbit tail", "Fingers are unusually long and flexible", "Has a skull-shaped birthmark", "Skin is rough like sandpaper", "Voice sounds like it’s coming from behind you", "Hair grows a few centimeters during the conversation", "Smells like ozone (like before a storm)",
        "Laugh sounds like breaking glass", "Has a scar that glows when magic is nearby", "Feet leave ash footprints", "Has a mole that looks like a small eye", "Skin has a slight bluish tint", "Has a bite mark from something very large", "Hands are always hot like embers", "Has an expression of absolute peace", "Gaze seems hypnotic", "Has a lock of hair that never stays still",
        "Eyes are completely black, no whites", "Has a small cross-shaped scar on the tongue", "Skin smells like old paper and parchment", "Has a crown-shaped burn mark", "Nails are metal (or seem to be)", "Has a voice that makes you want to trust them", "Their presence makes animals nervous", "Has a labyrinth tattoo on the palm of the hand", "Shadow is larger than it should be", "Has a star-shaped birthmark",
        "Skin has a metallic sheen", "Has an arrow scar on the neck", "Gaze seems to read your secrets", "Smells like wet earth", "Their presence is strangely comforting"
    ],

    ropas_extra: {
    poor:[
        "Wears rags that once were expensive silk",
        "Wears a cloak made from scraps of flags",
        "Wears boots that are three sizes too big",
        "Clothes covered in colorful leather patches",
        "Wears a belt made of hemp ropes",
        "Wears an apron covered in dried blood",
        "Clothes reeking of strong cheap perfume",
        "Wears a faded military uniform",
        "Clothes stained with wine and food",
        "Wears an extremely long wool scarf (3 meters)",
        "Wears rusty armor that squeaks",
        "Wears hunter’s clothes covered in leaves and mud",
        "Wears very worn sailor’s clothes",
        "Wears clothes made from potato sacks",
        "Wears monk’s robes, but carries weapons",
        "Wears a blacksmith’s apron with burn marks",
        "Wears clothing that looks like it’s made of dried seaweed",
        "Wears a red cloak with a frayed hem",
        "Wears clothes that are too small",
        "Wears a plain gray tunic with no markings",
        "Wears a coarse, itchy wool tunic",
        "Wears dockworker clothes",
        "Wears rawhide clothing"
    ],
    middle: [
        "Dressed entirely in a single color (e.g., yellow)",
        "Wears a tunic with forbidden religious symbols",
        "Wears clothing from a foreign culture",
        "Wears leather armor studded with coins",
        "Wears a hood that always hides their eyes",
        "Wears fingerless leather gloves",
        "Wears a cloak of crow feathers",
        "Wears a wide-brim hat with dangling bells",
        "Wears an immaculate white linen tunic",
        "Wears a tartan kilt from an unknown clan",
        "Wears a cloak that shines like oil",
        "Wears a tunic with hundreds of pockets",
        "Wears a tall hat with a crushed crown",
        "Wears a belt with a dragon-skull buckle",
        "Wears a travel cloak with a bear-hood",
        "Wears loud, clashing colors",
        "Wears snakeskin boots",
        "Wears strict mourning attire",
        "Wears armor made of treated wooden slats",
        "Wears impeccable riding clothes",
        "Wears a straw hat with dried flowers",
        "Wears a wide belt with four buckles",
        "Wears boots with spurs that are completely useless",
        "Wears explorer clothes full of sewn-on maps",
        "Wears a leather hat with protective goggles",
        "Wears formal clothes with mud stains",
        "Wears combat training clothes",
        "Wears a prayer mantle",
        "Wears a tunic with a large embroidered sun",
        "Wears nautical-style clothing",
        "Wears a hat shaped like a boat"
    ],

    wealthy: [
        "Wears a hat with a phoenix feather",
        "Dressed with aristocratic elegance, but barefoot",
        "Wears a transparent tunic over silk underwear",
        "Wears a belt packed with watchmaker tools",
        "Wears wolf furs, head still attached",
        "Wears a bronze breastplate polished like a mirror",
        "Wears an ermine-fur stole",
        "Wears a fur coat down to the ankles",
        "Wears formal clothes full of moth holes",
        "Wears a tunic with embroidered magical inscriptions",
        "Wears a blood-red velvet doublet",
        "Wears leather clothes with silver rivets",
        "Wears a jester hat without bells",
        "Wears a short cavalry officer’s cloak",
        "Wears a tunic with gold fringe",
        "Wears a coat with a peacock-feather collar",
        "Wears a silk tunic patterned with clouds",
        "Wears a tiger-fur cloak",
        "Wears a midnight-blue silk cloak"
    ]
},

ropas: {
    poor: [
        "Coarse linen tunic with leather elbow patches", "Dirty rags that once were gray", "Rough wool trousers tied with a hemp rope", "Leather apron stained with grease and soot", "Sheep-wool poncho, itchy and foul-smelling", 
        "Sun-faded shirt with moth holes", "Work clothes stained with dried mud and straw", "Wears only a leather loincloth and a burlap cape", "Worn rabbit-fur vest", "Sackcloth smock with arm slits",
        "Baggy trousers patched with different-colored fabrics", "Mendicant monk’s tunic, frayed at the edges", "Sailor clothes stiffened by salt and sweat", "Maid’s dress with a frayed hem", "Travel cloak with split seams and grease stains",
        "Nightshirt worn as street clothes", "Cracked leather breastplate from lack of oil", "Miner’s clothes covered in coal dust", "Heavy canvas skirt with torn pockets", "Short cloak made from old blanket scraps",
        "Mismatched boots tied with strips of cloth", "Linen underpants that are far too big", "Tunic with dye stains that won’t come out", "Shepherd’s clothes with bits of wool stuck to them", "Cheap-cloth doublet missing wooden buttons"
    ],
    middle: [
        "Well-tanned leather doublet with bronze buckles", "Cotton dress with simple floral embroidery", "Thick wool travel cloak with an iron brooch", "Reinforced riding pants and clean leather boots", "Scribe’s tunic with ink stains only on the cuffs",
        "Worn velvet vest, but clean", "Merchant clothes: practical, but made with good-quality fabrics", "Clerical habit with the holy symbol embroidered in white thread", "City guard uniform, somewhat faded", "Craftsman tabard with their guild’s seal",
        "Sunday dress with modest lace at the collar", "Reinforced travel outfit for the road", "Hooded cloak lined with fox fur", "Wool doublet with polished bone buttons", "Corduroy trousers and a pressed linen shirt",
        "Bard’s clothes: colorful, but clearly used", "Apothecary tunic with many small pockets", "Butcher’s apron of thick leather, clean", "Dark wool coat with a velvet collar", "Well-off peasant woman’s dress with several petticoats",
        "Wide-brim hat and oilcloth waterproof cape", "Tall riding boots with brass spurs", "Flexible leather gloves and a wool scarf", "Wide belt with neatly organized gear pouches", "Apprentice mage tunic with runes embroidered on the hem",
        "Blue wool jacket with reinforced cuffs for work", "Ochre-dyed linen dress with a tooled leather belt", "Tailor’s tabard with silver pins fastened to the chest", "Green corduroy doublet with suede elbow patches", "Rain cloak made of waxed canvas with a bone clasp",
        "Hardened leather bracers", "Traveling-merchant outfit with multiple inner pockets", "Soft leather bodice over a white cotton blouse", "Sturdy canvas trousers with mid-calf boots", "Wool vest with embroidered geometric motifs",
        "Simple temple tunic, but impeccably made", "Apothecary clothes stained with colorful chemical reagents", "Thick wool winter coat with pewter buttons", "Citizen’s dress with a simple lace overskirt", "Suede doublet with decorative copper threads",
        "Well-kept leather tool belt", "Felt hat with a small partridge feather", "Librarian tunic with wide, comfortable sleeves", "Innkeeper clothes: clean, with a cotton apron", "Short red wool cloak with a detachable hood",
        "Baggy linen trousers and a cheap-silk sash", "Teacher’s dress with a high collar and mother-of-pearl buttons", "Urban hunter’s doublet with reinforced shoulders", "Messenger tabard with the city’s coat of arms", "Wool jacket with carved wooden buttons",
        "Travel cloak lined with felt for the cold", "Short-brim hat with a satin ribbon", "Low-quality silk shirt with ruffles on the chest", "Herbalist dress with an apron full of pockets", "Leather jacket embossed with leaf patterns",
        "Leather boots with polished brass buckles", "University student tunic in academic colors", "Gardener clothes: practical, but made of tough fabric", "Synthetic-velvet doublet with cotton embroidery", "Simple party dress with colorful bows",
        "Minor ceremonial cloak with synthetic-fur trim", "Dark corduroy riding pants", "Linen blouse with black-thread embroidery", "Decoratively studded leather vest", "Low top hat with a silver buckle",
        "Musician clothes: flashy, but worn from travel", "Deacon’s tunic with a linen stole", "Wool jacket with a corduroy collar", "Wool dress with a belt of iron links", "Rain cloak with leather shoulder pads",
        "Leather side bag engraved with countryside scenes", "Goatskin work gloves", "Hand-spun silk scarf", "Fencing tunic with light padding", "Jeweler’s apron with hanging loupes"
    ],
    wealthy: [
        "Midnight-blue silk cloak with silver-thread edging", "Crimson velvet doublet with pearl buttons", "Gala dress with small gemstone inlays", "Translucent silk tunic over layers of fine linen", "Ceremonial plate armor engraved with gold filigree",
        "White ermine mantle with a solid-gold brooch", "Court attire with excessively long, decorated sleeves", "Silk dress with a rigid whalebone corset", "Exotic snakeskin boots with sharp tips", "Ostentatious hat with bird-of-paradise plumes",
        "Magistrate’s toga with purple stripes dyed with expensive pigment", "Riding suit of reinforced silk and dragon leather", "Iridescent cloak that changes color with the light", "Fine lace gloves and an ivory fan", "Belt of silver links with a large ruby in the buckle",
        "Foreign high fashion with asymmetrical cuts", "Archmage tunic with constellations embroidered in mithril", "Mantle of real peacock feathers", "Wedding dress with yards of lace and silk", "Gold brocade vest with heraldic motifs",
        "Short cloak of northern white-bear fur", "Silk breeches with dragons embroidered in gold thread", "Ornamental crystal cuirass for parades", "Wide-brim hat with a dangling jewel", "Gala tunic with rigid pauldrons plated in silver",
        "Snow-leopard fur cloak with a diamond brooch", "Silk doublet woven with threads of pure gold", "Gala dress with a long train laden with natural pearls", "Starlight-gauze tunic with magical light effects", "Polished silver cuirass decorated with epic reliefs",
        "Phoenix-feather mantle that emits a soft glow", "Starched, architectural lace ruff", "Black velvet dress sewn with diamonds", "Red dragon-leather boots with obsidian heels", "Gold headdress shaped like a radiant sun",
        "Senator’s toga embroidered with platinum thread", "Riding suit made of synthetic unicorn hide", "Scented cloak that releases sandalwood as they walk", "Spider-silk gloves with golden nails", "Mithril belt with an opal buckle",
        "Asymmetrical fashion from the Outer Planes", "Wizard tunic with runes that react to temperature", "Sabertooth tiger-fur mantle", "Wedding dress of iridescent mermaid silk", "Brocade vest with historical scenes",
        "Celestial-lamb wool cloak, white and ethereal", "Silk trousers threaded with ruby", "Corset of polished mother-of-pearl plates", "Wide-brim hat with a royal griffon plume", "Gala tunic with floating sleeves",
        "Arctic-fox coat with a purple silk lining", "Dueling suit of silk with hidden steel plates", "Ball gown that chimes like crystal bells", "Royal officer’s cloak with raised embroidery", "Ambassador tunic of the allied nations",
        "Basilisk-leather sandals with emeralds", "Gold mask covering only half the face", "Dress made of magically preserved petals", "Velvet jacket with ostrich-feather shoulder pads", "Silk travel cloak reinforced for nobles",
        "Hat with an integrated golden sundial", "Silk sleepwear threaded with silver", "High-rank priestly tunic with sacred gems", "Ceremonial mantle of dragon scales", "Doublet with a breastplate of inlaid pearls",
        "Black lace dress over crimson silk", "Silk gloves with decorative rings sewn on", "Suede boots embroidered with royal hunting scenes", "Velvet cloak with a rainbow-silk hood", "Luxury explorer tunic in manticore leather",
        "Necklace holding a gem the size of a bird egg", "Exotic-leather riding pants", "Jacket with crystal buttons containing will-o’-wisps", "Polar white-bear fur winter mantle", "Gala outfit with a levitating cape"
    ],
    aventurero: [
        "Studded leather armor full of battle nicks", "Camouflage cloak with sewn-on leaves and branches", "Tight leather clothes with sheaths for multiple daggers", "Travel cloak frayed by mountain winds", "Reinforced tunic with hidden metal mesh",
        "Explorer clothes with leather reinforcements on the knees", "Mercenary uniform stained with old blood", "Waterproof cloak made from monster hide", "Thick-soled boots made for mud and rock", "Warrior-monk outfit, simple but very durable",
        "Cross-belt with empty potion vials", "Leather pants with chainmail patches", "Dark tunic designed to blend into shadows", "Open-sea sailor clothes with thermal protection", "Wandering knight tabard with a worn shield",
        "Elven cloak that mimics the textures of the surroundings", "Barbarian clothing made of rough hides and bone trophies", "War cleric tunic with metal reinforcements", "Rogue outfit with dozens of hidden pockets", "Hardened leather poncho against projectiles",
        "Dungeon-delver outfit with hooks and ropes", "Hunter clothes that smell of forest musk", "Sorcerer tunic with spell-burns", "Padded armor under a simple travel cloak", "Reinforced veteran explorer boots"
    ]
},

wants: [
    "Get home as soon as possible to see their family", "Get enough money to pay off a gambling debt", "Find someone to help carry a heavy bundle", "Avenge a minor slight they received this morning", "Impress a superior to earn a promotion",
    "Get a date with someone who works at the tavern", "Avoid the guard questioning them at all costs", "Sell a 'magical' item they know is fake", "Find their missing pet (a ferret or a rat)", "Learn a new joke to tell at dinner",
    "Have someone listen to their very long personal story", "Find a cure for a persistent toothache", "Get the players to buy them a drink", "Find out who the outsider who just arrived is", "Recover a love letter that was stolen from them",
    "Prove they’re the best at their trade", "Make someone laugh at their misfortunes", "Get an autograph from a famous hero", "Get the players to give them a coin for a useless 'secret'", "Find a safe place to spend the night",
    "Bet on anything the players are doing", "Get rid of an object they think is bad luck", "Have someone help them read an official document", "Find out if their partner is cheating on them", "Get cheap supplies for their business",
    "Sneak into a private party they weren’t invited to", "Get the guard to arrest their business rival", "Buy a birthday present for their child", "Figure out what’s inside a suspicious package", "They just want someone to treat them with respect",
    "Get a secret recipe from a neighboring village", "Prove dragons don’t exist (or that they do)", "Get the players to carry a message to the neighboring city", "Win a local eating or drinking contest", "Recover a tool they pawned out of necessity",
    "Have someone help move a stuck cart", "Find an excuse not to go to work today", "Know the exact time every five minutes", "Get the players to talk about their faraway lands", "Get a 'treasure map' they saw at a market stall",
    "Make sure nobody touches their belongings", "Find a rare ingredient for a special dinner", "Pass themself off as someone more important", "Have someone confirm their clothes are in fashion", "Avoid running into a creditor who’s nearby",
    "Find an expert to appraise a jewel", "Have someone explain what magic is", "Get a job as a temporary bodyguard", "Convince someone to join their cult (kind of ridiculous)", "Get repaid for a favor they did years ago",
    "Make the players try their new invention", "Find out if it’s true the King is sick", "Clear their good name after a misunderstanding", "Have someone help get a cat down from a rooftop", "Find their long-lost twin sibling",
    "Have someone translate an elvish word for them", "Bet their last coin on a tavern brawl", "Have the players tell them a scary story", "Find a remedy for baldness", "Be remembered as a hero, even if only for a day",
    "Get an invitation to the masquerade ball", "Find out who stole their clothes while they were bathing", "Make a business deal with the players", "Have someone hold a torch for a moment", "Find a lucky stone (or just an ordinary pebble)",
    "Find out where the black market is hiding", "Get a hair dye that isn’t green", "Have someone help write an elegy", "Find an excuse to drink for free", "Discover their boss’s weak spot",
    "Convince the players to buy their old donkey", "Get someone to carry them in their arms for a bit", "Find a shoe they lost", "Have someone defend them from a thug", "Find out if the players are real or illusions",
    "Get an illegal hunting permit", "Have someone read their future", "Find a source of pure water", "Have the players stay for dinner at their house", "Get a confession out of a thief",
    "Sell their soul to the highest bidder (literally)", "Make the bard play their favorite song", "Have someone help hide a body (an animal, they swear)", "Find a coin they dropped in the sewer", "Get the players to adopt them",
    "Figure out what a recurring dream means", "Get someone to buy them a new pair of boots", "Find someone who knows heraldry", "Have the players help them practice fencing", "Get an ingredient for a weak poison",
    "Find out why everyone is looking at them weird", "Have someone hold their hat", "Find a needle in a haystack (literally)", "Have the players sign a 'good citizen' document", "Get a real love potion",
    "Find out whether elves really don’t sleep", "Have someone clean their boots", "Find a family treasure in a tomb", "Have the players teach them a magic trick", "Get forgiveness from an old enemy"
],
// --- SECRETS (TWISTS) ---
twists: [
    "They’re a spy for an enemy faction",
    "They’re actually a werewolf (but they don’t know it)",
    "They carry a cursed object that forces them to lie",
    "They’re a fugitive noble disguised as a commoner",
    "They can’t read, but they constantly pretend they can",

    "They’re a rookie doppelganger who forgets details",
    "In their spare time, they’re a famous hired killer",
    "They’re under the effect of a 'Modify Memory' spell",
    "They’re carrying a bag with 500 stolen gold pieces",
    "They’re a ghost who doesn’t know they’re dead",

    "They owe a blood debt to a demon",
    "They’re actually two halflings stacked on top of each other",
    "They’re the true heir to the local throne",
    "They were sent to assassinate one of the players",
    "They know where the city’s treasure is buried",

    "They’re a religious fanatic of a forbidden god",
    "They have a map tattooed on their scalp",
    "Their shadow sometimes moves independently",
    "They’re actually a young dragon in disguise",
    "They’re possessed by the spirit of a prankster bard",

    "They poisoned the tavern food (by accident)",
    "They’re a time traveler from a future era",
    "They work for the campaign’s main villain",
    "They’re actually a criminal wanted in three kingdoms",
    "They made a pact to be immortal, but only if they never blink",

    "They’re a poison expert and carry several poisons on them",
    "Their clothes are actually a tamed mimic",
    "They’re looking for the players to propose marriage",
    "They’re the author of all the city’s gossip books",
    "They’re cursed so animals can talk to them",

    "They’re a veteran of a war that never happened",
    "They’re carrying an exotic creature’s egg in their backpack",
    "They’re actually a level 20 wizard who has lost their memory",
    "Their family was killed by someone who resembles a player",
    "They’re an informant for the city watch",

    "They’re infected with a contagious magical disease",
    "They’re actually a puppet controlled by invisible strings",
    "They’re the leader of a local thieves’ guild",
    "They carry a secret message written on their skin in invisible ink",
    "They’re a refugee from another plane of existence",

    "Their 'pet' is actually their warlock patron",
    "They’re afraid of magic and panic if they see it",
    "They’re an expert in locks and traps",
    "They stole the temple’s sacred chalice this morning",
    "They’re actually an undercover tavern critic",

    "They have amnesia and think the players are their children",
    "They wear a ring that lets them hear nearby thoughts",
    "They’re a spy watching the players, sent by an ally",
    "Their family is a vampire bloodline (they’re not one yet)",
    "They have an evil twin nearby",

    "They carry an object that is the key to an ancient prison",
    "They’re a scholar seeking a human sacrifice",
    "They’re actually a famous bard, tired of fame",
    "They have a birthmark that says they’re 'the chosen one'",
    "They’re a double (or triple) agent",

    "Their voice is the result of a botched silence spell",
    "They carry a letter that proves a royal conspiracy",
    "They’re actually a highly advanced mechanical construct",
    "They’re dead inside (literally: an intelligent undead)",
    "They collect eyes from different species",

    "They think the world is a simulation (or a dice game)",
    "They’re a deserter from an infernal legion",
    "They have a tiny fairy trapped in a jar",
    "They’re an expert in the language of dragons",
    "Their family sold them to a witch when they were a child",

    "They carry a legendary weapon but think it’s a fake",
    "They’re an artist who paints the future",
    "They have a pact with a being from the Plane of Dreams",
    "They’re actually the city’s mayor in disguise",
    "They know how to get into the royal treasury",

    "They’re a reformed cannibal (or maybe not)",
    "They wear a pendant that is a lich’s phylactery",
    "They’re a sailor who has never seen the sea",
    "They have an irrational phobia of elves (or dwarves)",
    "They’re a stowaway on a flying ship",

    "Their breath can kill flies instantly",
    "They carry a jewel that is the heart of an elemental",
    "They’re a monk who broke their vow of silence today",
    "They’re actually a bounty hunter looking for the players",
    "They’re a messenger carrying a message they altered themselves",

    "They know the true name of a powerful demon",
    "They’re addicted to a rare potion",
    "They collect adventurers’ teeth",
    "They’re a noble turned into a commoner by a wish",
    "They carry a secret that would destroy the local church",

    "They’re an expert at counterfeiting platinum coins",
    "Their shadow has horns, even though they don’t",
    "They’re an ancient hero who was resurrected wrong",
    "They keep a journal of everyone they’ve killed",
    "They guard an entrance to the Underworld",

    "They have a silver tongue (literally: made of metal)",
    "They’re an infiltrator from a secret society of mages",
    "They know who the traitor is in the players’ group",
    "They carry a curse that attracts lightning",
    "They’re a cook who uses 'humanoid' ingredients",

    "They’re actually an avatar of a bored minor god",
    "They’re obsessed with the players and follow them everywhere",
    "They have a treasure map tattooed on their tongue",
    "They’re an ex-cultist fleeing their former brethren",
    "They know how to stop the end of the world (but it’s very expensive)"
]
};

