const DATA = {
    especies: [
        // --- Jugables (PHB 2024 + Favoritas) ---
        "Humano", "Elfo", "Enano", "Mediano", "Tiefling", 
        "Dracónido", "Gnomo", "Orco", "Goliath", "Aasimar",
        "Warforged", "Tortle", "Leonin", "Aarakocra", "Genasi", "Loxodon",
        // --- Humanoides Extras ---
        "Goblin", "Kobold", "Tabaxi", "Kenku", "Githyanki"
    ],
    
    nombres: {
        // --- Jugables Core ---
        "Humano": [
            "Alaric", "Elara", "Garrick", "Vera", "Kaelen", "Rowan", "Mina", "Osric", "Soren", "Talia",
            "Benedict", "Cassandra", "Darian", "Elowen", "Falk", "Gemma", "Harlan", "Iris", "Jovan", "Kira",
            "Leif", "Mira", "Nolan", "Ophelia", "Pike", "Quentin", "Runa", "Silas", "Thea", "Valerius", 
            "Adelaide", "Balthazar", "Cillian", "Daphne", "Eamon", "Freya", "Gideon", "Hester", "Isidore", "Jocelyn",
            "Kael", "Liora", "Maddock", "Nyssa", "Orion", "Phineas", "Quintessa", "Roderick", "Saskia", "Tobias",
            "Ursula", "Valen", "Winifred", "Xavier", "Yvaine", "Zephyr", "Aldous", "Beatrix", "Cyprian", "Dorothea",
            "Evander", "Florence", "Gregory", "Hilda", "Ignatius", "Julian", "Kassandra", "Lucius", "Maude", "Nathaniel",
            "Octavia", "Percival", "Quinn", "Rosalind", "Sebastian", "Tatiana", "Ulysses", "Victoria", "Wyatt", "Zoraida"
        ],
        "Elfo": [
            "Thaelan", "Faenora", "Kyriel", "Sariel", "Elowen", "Meryn", "Valerius", "Iandir", "Arannis", "Lia",
            "Adran", "Aelar", "Aramil", "Arariel", "Enna", "Felosial", "Ielenia", "Keyleth", "Leshanna", "Mialee",
            "Naivara", "Quelenna", "Sariel", "Shanairra", "Theirastra", "Thia", "Vadania", "Valanthe", "Xanaphia", "Zinakas"
        ],
        "Enano": [
            "Brundor", "Thorina", "Gimli", "Dagna", "Hogar", "Kilda", "Ulfgar", "Bardel", "Orsik", "Vistra",
            "Adrik", "Alberich", "Baern", "Barendd", "Brottor", "Dain", "Darrak", "Delg", "Eberk", "Einkil",
            "Fargrim", "Flint", "Gardain", "Harbek", "Kildrak", "Morgran", "Rurik", "Taklinn", "Thoradin", "Tordek"
        ],
        "Mediano": [
            "Bilbo", "Rosie", "Pippin", "Tilly", "Finnan", "Lidda", "Merric", "Cora", "Reed", "Paela",
            "Alton", "Ander", "Cade", "Corrin", "Eldon", "Garret", "Lyle", "Milo", "Osborne", "Roscoe",
            "Wellby", "Andry", "Bree", "Callie", "Chenna", "Euphemia", "Gillian", "Kithri", "Lavinia", "Nedda"
        ],
        "Tiefling": [
            "Maldición", "Esperanza", "Ceniza", "Rigor", "Malicia", "Cariño", "Venganza", "Gula", "Credo", "Artesía",
            "Abadón", "Akmenos", "Amnon", "Barakas", "Damakos", "Ekemon", "Iados", "Kairon", "Leucis", "Melech",
            "Mordai", "Morthos", "Pelaios", "Skamos", "Therai", "Anakis", "Bryseis", "Criella", "Damaia", "Ea"
        ],
        "Dracónido": [
            "Arjhan", "Balasar", "Donaar", "Ghesh", "Kriv", "Medrash", "Nadarr", "Patrin", "Rhogar", "Sora",
            "Pandjed", "Bharash", "Bivrua", "Donaar", "Ghesh", "Heskan", "Kriv", "Medrash", "Mehen", "Nadarr",
            "Patrin", "Rhogar", "Shamash", "Shedinn", "Tarhun", "Torinn", "Akra", "Biri", "Daar", "Farideh"
        ],
        "Gnomo": [
            "Boddynock", "Dimble", "Fonkin", "Gimble", "Namfoodle", "Roondar", "Zook", "Lilli", "Pip", "Nissa",
            "Alston", "Alvyn", "Boddynock", "Brocc", "Burgell", "Dimble", "Eldon", "Erky", "Fonkin", "Frug",
            "Gerbo", "Gimble", "Glim", "Jebeddo", "Kellen", "Namfoodle", "Orryn", "Roondar", "Seebo", "Sindri"
        ],
        "Orco": [
            "Brugh", "Drog", "Garak", "Korg", "Mug", "Raza", "Thokk", "Varg", "Lurka", "Urzul",
            "Dench", "Feng", "Gell", "Henk", "Holg", "Imsh", "Keth", "Krusk", "Mhurren", "Ront",
            "Shump", "Thokk", "Baggi", "Emen", "Engong", "Kansif", "Myev", "Neega", "Ovak", "Ownka"
        ],
        "Goliath": [
            "Aukan", "Ehalu", "Gae-Al", "Kavak", "Lo-Kag", "Maveith", "Thalai", "Uthal", "Vakora", "Keothi",
            "Anakalathai", "Elanithino", "Gathakanathi", "Kalagiano", "Kolae-Gileana", "Oglakanu", "Thuliaga", "Thunukalathi", "Vaquano", "Vunavue-Maveith",
            "Aguilero", "Bearkiller", "Dawnwatcher", "Fearless", "Flintfinder", "Horncarver", "Mountainclimber", "Riverjumper", "Skywatcher", "Steadyhand"
        ],
        "Aasimar": [
            "Aasir", "Balthazar", "Casiel", "Dariel", "Ephraim", "Gabriel", "Hadriel", "Ithuriel", "Remiel", "Zariel",
            "Uriel", "Sariel", "Raziel", "Ramiel", "Ophaniel", "Muriel", "Jophiel", "Israfil", "Haniel", "Dumah",
            "Daniel", "Castiel", "Barachiel", "Azrael", "Aniel", "Amitiel", "Adriel", "Abasdarhon", "Abaddon", "Zaphkiel"
        ],
        "Warforged": [
            "Yunque", "Martillo", "Siete", "Centinela", "Bastión", "Corte", "Óxido", "Perno", "Unidad 42", "Cero",
            "Acero", "Baluarte", "Cañón", "Daga", "Eje", "Forja", "Granito", "Hierro", "Junta", "Kilovatio",
            "Lanza", "Muesca", "Níquel", "Ónice", "Plomo", "Quilla", "Radar", "Sierra", "Torre", "Viga"
        ],
        "Tortle": [
            "Kome", "Mudlow", "Platón", "Tortu", "Grum", "Oog", "Shellon", "Pok", "Quill", "Gourd",
            "Burt", "Clyde", "Dung", "Ebb", "Flo", "Gully", "Hunk", "Itch", "Jabb", "Krug",
            "Lump", "Muck", "Nog", "Oat", "Puff", "Quah", "Rudge", "Snout", "Tug", "Urth"
        ],
        "Leonin": [
            "Ajani", "Hmar", "Kytheon", "Makos", "Pyxis", "Rago", "Tethos", "Zora", "Lio", "Mufar",
            "Atreos", "Brutus", "Cástor", "Dymas", "Erebo", "Fobos", "Gorgas", "Helios", "Ícaro", "Jano",
            "Kórax", "Licos", "Midas", "Nereo", "Orión", "Palas", "Quirón", "Rómulo", "Silas", "Tifón"
        ],
        "Aarakocra": [
            "Aera", "Fierka", "Oerk", "Qiik", "Rikth", "Zark", "Klee", "Praw", "Gyr", "Akra",
            "Chirr", "Dakk", "Eek", "Fffr", "Grrr", "Hrrr", "Iikk", "Jrrr", "Krrr", "Lrrr",
            "Mrrr", "Nrrr", "Orrr", "Prrr", "Qrrr", "Rrrr", "Srrr", "Trrr", "Urrr", "Vrrr"
        ],
        "Genasi": [
            "Brasa", "Ráfaga", "Marea", "Pedernal", "Céfiro", "Magma", "Rocío", "Cuarzo", "Ignis", "Aqua",
            "Humo", "Siroco", "Tizón", "Escarcha", "Limo", "Guijarro", "Nube", "Torrente", "Ceniza", "Vapor",
            "Orizonte", "Abismo", "Sima", "Cumbre", "Páramo", "Selva", "Duna", "Coral", "Azufre", "Ámbar"
        ],
        "Loxodon": [
            "Bayu", "Ganesha", "Illo", "Luma", "Thrum", "Vanu", "Oman", "Pagu", "Kandu", "Boro",
            "Aru", "Bava", "Cavun", "Duma", "Eshat", "Fandun", "Ganesh", "Huna", "Indu", "Jandun",
            "Kanu", "Luma", "Mava", "Nandu", "Onu", "Pava", "Ranu", "Savu", "Thrum", "Vanu"
        ],

        "Goblin": [
            "Droop", "Snot", "Griz", "Punt", "Vark", "Zix", "Splug", "Klarg", "Boogle", "Dobby",
            "Gazza", "Jib", "Knox", "Ludo", "Mog", "Nix", "Ozzy", "Pox", "Ratty", "Skab",
            "Titch", "Vex", "Wiz", "Yappy", "Zog", "Bite", "Chomp", "Gnash", "Snap", "Snarl"
        ],
        "Kobold": [
            "Meepo", "Ikk", "Sniv", "Kipe", "Zat", "Grak", "Pook", "Vix", "Kura", "Saka",
            "Daks", "Eek", "Fik", "Gark", "Heks", "Ip", "Jaks", "Kip", "Lek", "Mek",
            "Neks", "Ok", "Pek", "Qak", "Reks", "Sik", "Tik", "Uks", "Vik", "Zek"
        ],
        "Tabaxi": [
            "Río en la Noche", "Sombra de Árbol", "Cinco Espejos", "Pluma de Viento", "Gato de Nieve", "Nube Lejana",
            "Canto de Grillo", "Luz de Estrellas", "Paso de Trueno", "Ojo de Tormenta", "Garra de Hierro", "Susurro de Hojas",
            "Roca Solitaria", "Valle Profundo", "Cumbre Nevada", "Rocío de Mañana", "Llama Eterna", "Viento del Norte",
            "Arena Caliente", "Bosque Oscuro", "Mar de Cristal", "Luna de Sangre", "Sol de Invierno", "Camino Largo",
            "Puente de Plata", "Torre de Marfil", "Cueva Profunda", "Río Rápido", "Pradera Verde", "Cielo Azul"
        ],
        "Kenku": [
            "Graznido", "Clanc", "Eco", "Susurro", "Óxido", "Silbido", "Chasquido", "Golpe", "Crujido", "Zumbido",
            "Silbato", "Campana", "Martillazo", "Goteo", "Rugido", "Chirrido", "Explosión", "Viento", "Trueno", "Lluvia",
            "Fuego", "Cristal", "Papel", "Cadena", "Puerta", "Pasos", "Risa", "Llanto", "Grito", "Canto"
        ],
        "Githyanki": [
            "Arrak", "Gaath", "Hrath", "K'lyss", "Madar", "R'ayth", "Vlaakith", "Zar-Ek", "Xam", "Yuan",
            "Zal", "Arak", "Baal", "Caar", "Daar", "Eer", "Faar", "Gaar", "Haar", "Iiar",
            "Jaar", "Kaar", "Laar", "Maar", "Naar", "Oaar", "Paar", "Qaar", "Raar", "Saar"
        ]
    },
    



"Nombres_Globales": [
    "Abraxas", "Adonais", "Aglon", "Akra", "Amara", "Anathel", "Antua", "Argus", "Arlow", "Asha", 
    "Azriel", "Bael", "Barda", "Belial", "Beryn", "Blain", "Boaz", "Borg", "Brant", "Bryn", 
    "Caelum", "Calix", "Candra", "Cato", "Cax", "Celes", "Chard", "Ciro", "Colm", "Corvus", 
    "Dael", "Dagon", "Dante", "Dara", "Dax", "Demitri", "Doran", "Draven", "Duer", "Duma", 
    "Egan", "Eira", "Elian", "Elowan", "Emet", "Enzo", "Eris", "Esme", "Ezra", "Fael", 
    "Fane", "Faust", "Fenyx", "Fionn", "Flint", "Flynn", "Galan", "Gant", "Garek", "Gavin", 
    "Gora", "Grendel", "Hadar", "Halia", "Harko", "Haze", "Hestia", "Hollis", "Hyram", "Idris", 
    "Igon", "Ilara", "Inaya", "Indra", "Iori", "Iskan", "Iva", "Izar", "Jace", "Jada", 
    "Jarek", "Jarl", "Jaya", "Jedd", "Jinx", "Joren", "Kael", "Kai", "Kaly", "Kano", 
    "Kazi", "Kean", "Kento", "Kiba", "Koda", "Kaelen", "Lael", "Lark", "Lazar", "Leda", 
    "Lian", "Lobo", "Loke", "Loran", "Lumi", "Mace", "Malik", "Maren", "Maro", "Mura", 
    "Nadir", "Nala", "Nao", "Narek", "Nero", "Niles", "Nix", "Nova", "Nox", "Nyx", 
    "Odin", "Olam", "Onyx", "Oren", "Orion", "Orla", "Osias", "Otho", "Oz", "Paxon", 
    "Phaedra", "Pyre", "Qad", "Quon", "Radek", "Raiden", "Rave", "Raya", "Razo", "Remi", 
    "Rhea", "Rico", "Rogue", "Runa", "Ryker", "Saba", "Saffron", "Saka", "Saren", "Sayer", 
    "Seth", "Shade", "Sira", "Sloane", "Soren", "Stark", "Sya", "Talon", "Tarek", "Thane"
],


profesiones: {
    pueblo: {
        pobre: [
            "Campesino jornalero",
            "Granjero de nabos",
            "Pastor de ovejas",
            "Leñador",
            "Mozo de cuadra",
            "Pescador de río",
            "Cazador de trampas",
            "Recolector de miel",
            "Recogedor de turba",
            "Carbonero",
            "Segador",
            "Criador de cerdos",
            "Techador de paja",
            "Vendedor de leña",
            "Ayudante de parto (animales)",
            "Guardián de granero",
            "Escardador",
            "Hachero",
            "Vigilante nocturno de campo",
            "Recolector de hierbas",
            "Mozo de taberna rural",
            "Lavandera de río",
            "Criador de ocas",
            "Cortador de turba",
            "Excavador de zanjas",
            "Esquilador",
            "Transportista de grano",
            "Espigador",
            "Mozo de molino",
            "Pescador de anguilas",
            "Cargador de fardos",
            "Boyero",
            "Limpiador de establos",
            "Vendedor de forraje",

            // NUEVAS
            "Recolector de leña húmeda",
            "Desenterrador de raíces",
            "Guardador de cabras",
            "Recolector de ortigas",
            "Cuidador de cerdos ajenos",
            "Peón de siega",
            "Arreador de mulas",
            "Portador de agua",
            "Recolector de estiércol",
            "Barrendero de plaza rural",
            "Reparador de cercas",
            "Trillador manual",
            "Recolector de manzanas silvestres",
            "Cuidador de gallinas",
            "Remendador de redes",
            "Pelador de corteza",
            "Pastor trashumante",
            "Recolector de setas",
            "Guardia de campos comunales",
            "Desbrozador",
            "Cargador de troncos",
            "Recolector de lino",
            "Mozo de herrador",
            "Jornalero de viña",
            "Cuidaniños campesino",
            "Peón de arado",
            "Recolector de nueces",
            "Guardián de ovejas enfermas",
            "Limpiador de acequias",
            "Cuidador de colmenas"
            ],
        media: [
            "Molinero",
            "Herrador",
            "Curtidor",
            "Tejedora de lana",
            "Cantero",
            "Fabricante de velas",
            "Cervecero rural",
            "Toneler",
            "Pocero",
            "Salinero",
            "Arriero",
            "Cestero",
            "Molinero de grano",
            "Domador de bueyes",
            "Apicultor",
            "Quesero artesano",
            "Escobillero",
            "Peletero de aldea",
            "Fabricante de arados",
            "Hojalatero ambulante",
            "Vaquero",
            "Alfarero de barro rojo",
            "Busca-trufas",
            "Podador de frutales",
            "Guardabosques menor",
            "Cocinero de comunas",
            "Remendón de aperos",
            "Prensador de sidra",
            "Recolector de bayas",
            "Cuidador de huertos",
            "Fabricante de sogas",
            "Afilador de guadañas",

            // NUEVAS
            "Maestro de escuela rural",
            "Administrador de tierras comunales",
            "Tabernero del pueblo",
            "Maestro carpintero rural",
            "Maestro cantero",
            "Sanador de aldea",
            "Veterinario rural",
            "Dueño de molino",
            "Administrador de granja grande",
            "Tratante de ganado",
            "Guardia forestal",
            "Recolector de impuestos rurales",
            "Escribano del pueblo",
            "Organizador de ferias",
            "Maestro panadero rural",
            "Criador de caballos de tiro",
            "Inspector de cosechas",
            "Propietario de viñedo pequeño",
            "Encargado de bodega",
            "Administrador de establos",
            "Comerciante itinerante",
            "Maestro herrero rural",
            "Carpintero de carretas",
            "Fabricante de barriles",
            "Curandero reconocido",
            "Maestro tejedor",
            "Encargado del granero comunal",
            "Capataz de campos",
            "Proveedor de semillas",
            "Recolector de rentas"
            ]
    },
    ciudad: {
        pobre: [
        "Jefe de cuadrilla",
        "Estibador",
        "Remero de barcaza",
        "Mensajero de a pie",
        "Palafrenero",
        "Barbero-Cirujano",
        "Dentista ambulante",
        "Malabarista de calle",
        "Tragafuegos",
        "Encantador de serpientes",
        "Pregonero",
        "Farolero (enciende luces)",
        "Sereno",
        "Recadero",
        "Limpiabotas",
        "Afilador",
        "Vendedor de flores",
        "Vendedor de pasteles",
        "Aguaor",
        "Encordador de ballestas",
        "Pintor de brocha gorda",
        "Limpiador de chimeneas",
        "Rata de alcantarilla (limpiador)",
        "Cazador de ratas",
        "Alguacil",
        "Guardia de la puerta",
        "Carcelero",
        "Verdugo",
        "Torturador oficial",
        "Cobrador de peajes",
        "Ladrón de bolsillos",
        "Falsificador de documentos",
        "Contrabandista de licor",
        "Traficante de venenos",
        "Asesino a sueldo",
        "Matón de taberna",
        "Extorsionador",
        "Limpiador de escenas del crimen",
        "Timador de calle",
        "Apostador profesional",
        "Corredor de apuestas ilegales",
        "Pugilista",
        "Buscavidas",
        "Vagabundo",
        "Mendigo profesional",
        "Recogedor de basura",
        "Chatarrero",
        "Cazador de tesoros de cloaca",
        "Médium",
        "Adivino de feria",
        "Lectura de cartas",
        "Alquimista de calle (drogas)",
        "Traficante de sueños",
        "Mercenario sin contrato",
        "Desertor",
        "Pirata de río",
        "Saqueador de tumbas",
        "Vendedor de órganos",
        "Embaucador",
        "Tahúr",
        "Lanza-cuchillos",
        "Informante de los bajos fondos",
        "Pícaro de tejado",
        "Mula de carga",
        "Encubridor de objetos robados",
        "Falsificador de arte",
        "Chamán de suburbio",
        "Fanático religioso de esquina",
        "Profeta del fin del mundo"
        ],
        media: [
        "Relojero (o mecánico de engranajes)",
        "Boticario",
        "Librero",
        "Soplador de vidrio",
        "Cuchillero",
        "Cerrajero de seguridad",
        "Zapatero de corte",
        "Sombrerero",
        "Tintorero",
        "Tapicero",
        "Mueblista",
        "Broncista",
        "Especiero",
        "Repostero",
        "Charcutero",
        "Vendedor de mapas",
        "Aparejador",
        "Contratista de obras",
        "Capataz de puerto",
        "Capitán de ferry",
        "Aduanero",
        "Pesador público",
        "Tasador de impuestos",
        "Escribano público",
        "Preceptor nocturno",
        "Barbero-Cirujano",
        "Bañero de termas",
        "Maquillador de teatro",
        "Actor de comedia",
        "Tragediante",
        "Domador de fieras",
        "Gladiador retirado",
        "Músico de cámara",
        "Bailarín de salón",
        "Maestro de esgrima",
        "Instructor de equitación",
        "Bibliotecario de la Gran Torre",
        "Archivero",
        "Copista",
        "Traductor de lenguas muertas",
        "Herbolario urbano",
        "Partera de la ciudad",
        "Médico de peste",
        "Embalsamador",
        "Guía turístico de las ruinas",
        "Vigilante de mercado",
        "Conductor de carruaje",
        "Cocinero de posada",
        "Sumiller",
        "Crupier de casino",
        "Anfitrión de club",
        "Crítico gastronómico",
        "Corresponsal",
        "Cartero",
        "Tatuador",
        "Mecánico de carretas",
        "Inspector de sanidad",
        "Vigilante de incendios",
        "Censor de libros",
        "Inquisidor",
        "Maestro de ceremonias",
        "Heraldo de torneos",
        "Árbitro de duelos",
        "Portavoz del gremio",
        "Líder sindical"
        ],
        rica: [
        "Joyero real",
        "Sastre de seda",
        "Peletero de lujo",
        "Pintor de retratos",
        "Escultor de mármol",
        "Grabador de sellos",
        "Mercader de especias",
        "Cambista de moneda",
        "Usurero",
        "Prestamista",
        "Dueño de casa de empeño",
        "Exportador de vinos",
        "Importador de sedas",
        "Vendedor de antigüedades",
        "Luthier (laúdes)",
        "Armero fino",
        "Perfumista",
        "Incrustador de nácar",
        "Platero",
        "Orfebre",
        "Comerciante de gemas",
        "Tratante de arte",
        "Sommelier de taberna cara",
        "Maestro chocolatero",
        "Panadero de palacio",
        "Mercader de esclavos (o sirvientes)",
        "Tratante de caballos de guerra",
        "Suministrador de barcos",
        "Arquitecto",
        "Ingeniero civil",
        "Notario",
        "Abogado defensor",
        "Magistrado",
        "Diplomático",
        "Embajador de paso",
        "Espía de la corona",
        "Comisario de distrito",
        "Intendente",
        "Sumiller de palacio",
        "Mayordomo de casa noble",
        "Secretario personal",
        "Tesorero de gremio",
        "Cortesana de alto standing"
        ]
    }


},


    estados: [
        "Hostil", 
        "Neutral", 
        "Amistoso", 
    ],

    voces: [
        // --- Volumen y Tono ---
        "Volumen ALTO y tono GRAVE (Voz de mando/autoridad)",
        "Volumen BAJO y tono AGUDO (Voz tímida o infantil)",
        "Susurro constante y tono NEUTRO (Como si compartiera un secreto)",
        "Volumen NORMAL pero tono MUY GRAVE (Voz cavernosa/imponente)",
        "Grito constante y tono AGUDO (Parece siempre al borde de un ataque de pánico)",
        
        // --- Velocidad y Ritmo ---
        "Habla MUY RÁPIDO y atropellado (Ansiedad o exceso de energía)",
        "Habla MUY LENTO, saboreando cada sílaba (Aburrimiento o extrema vejez)",
        "Ritmo entrecortado, hace pausas... en lugares... extraños",
        "Habla sin respirar, frases larguísimas que terminan en un suspiro",
        "Habla de forma rítmica, casi como si estuviera recitando un poema",

        // --- Textura y Calidad (Fácil de imitar) ---
        "Nasal (Como si tuviera la nariz tapada)",
        "Rasposa/Aguardentosa (Como si necesitara aclarar la garganta)",
        "Voz de aire (Exhala mucho aire al hablar, voz etérea/fantasmagórica)",
        "Voz gutural (Habla desde el fondo de la garganta, muy vibrante)",
        "Voz apretada (Habla con los dientes casi cerrados)",
        "Voz chillona (Fuerza la garganta hacia arriba)",
        
        // --- Tics y Manierismos de Acting ---
        "Repite la última palabra de cada frase (frase... frase)",
        "Sisea las 'S' de forma exagerada (como una serpiente)",
        "Gruñe o resopla entre frases",
        "Habla mientras ríe nerviosamente por nada",
        "Termina cada frase como si fuera una pregunta?",
        "Chasquea la lengua antes de empezar a hablar",
        "Tartamudea solo al pronunciar nombres propios",
        "Habla con la boca llena (o finge que mastica algo)",
        "Carraspea constantemente para interrumpir a los demás",
        "Habla con un tono monótono, sin ninguna emoción (robot/zombie)",
        "Voz melosa y exageradamente educada (sospechoso)",
        "Habla con un bostezo constante, como si fuera a quedarse dormido",
        "Voz jadeante, como si acabara de correr un maratón",
        "Habla inhalando aire en lugar de exhalando (voz de susto)",

        // --- Combinaciones Técnicas ---
        "Bajo, Grave y Lento (Villano calculador)",
        "Alto, Agudo y Rápido (Vendedor callejero frenético)",
        "Normal, Nasal y Lento (Burocrata aburrido)",
        "Bajo, Rasposo y Rápido (Conspirador de callejón)",
        "Alto, Neutro y con Pausas (Profeta iluminado)",
        "Susurro, Agudo y Siseante (Criatura rastrera)",
        "Grave, Rápido y con Voz Apretada (Militar estresado)",
        "Normal, Aireado y Melódico (Noble distraído)"
    ],

    acting: [
        // --- Tics y Gestos Nerviosos ---
        "Se muerde las uñas de forma compulsiva",
        "Se rasca constantemente el cuello, como si le picara una etiqueta",
        "Juega con un anillo en su dedo, quitándoselo y poniéndoselo",
        "Parpadea excesivamente rápido cuando le hacen preguntas",
        "Se toca el lóbulo de la oreja izquierda repetidamente",
        "Tamborilea con los dedos sobre cualquier superficie cercana",
        "Se ajusta las gafas (o un parche imaginario) cada pocos segundos",
        "Se humedece los labios constantemente con la lengua",
        "Se limpia sudor imaginario de la frente con un pañuelo sucio",
        "Se enrolla un mechón de pelo en el dedo sin parar",

        // --- Con Objetos (Props) ---
        "Está fumando una pipa que desprende un humo azulado y denso",
        "Limpia obsesivamente una daga (o una cuchara) con un trapo",
        "Está bebiendo un té muy caliente, soplando ruidosamente",
        "Lanza una moneda al aire y siempre la atrapa",
        "Masca una raíz de regaliz o un trozo de cuero",
        "Afila un lápiz o talla un trozo de madera con un cuchillo",
        "Hojea un libro pequeño y arrugado, ignorando a veces a los jugadores",
        "Juega con un juego de dados en una mano, haciéndolos chocar",
        "Está comiendo algo pequeño (frutos secos, bayas) uno por uno",
        "Limpia sus uñas con la punta de un alfiler",

        // --- Postura y Estado Físico ---
        "Está extremadamente relajado, casi desparramado en su asiento",
        "Se mantiene rígido como una tabla, con las manos tras la espalda",
        "Está inclinado hacia adelante, invadiendo el espacio personal de los jugadores",
        "Se balancea sobre sus talones de forma rítmica",
        "Tiene los brazos cruzados con tanta fuerza que parece enfadado",
        "Mantiene la cabeza ladeada, como si escuchara una voz interna",
        "Se encoge de hombros constantemente mientras habla",
        "Se frota las manos como si tuviera frío permanentemente",
        "Se apoya pesadamente sobre un bastón o sobre la mesa",
        "Mira siempre por encima del hombro, como si alguien le siguiera",

        // --- Gestos de Actuación (Acting) ---
        "Evita el contacto visual directo, mirando siempre al suelo",
        "Mira fijamente a los ojos de su interlocutor sin parpadear",
        "Señala con el dedo índice para recalcar cada palabra",
        "Asiente con la cabeza a todo lo que dicen, incluso antes de terminar",
        "Se tapa la boca con la mano cada vez que se ríe",
        "Entorna los ojos, como si no viera bien de cerca",
        "Se acaricia la barba (tenga o no) de forma pensativa",
        "Mueve las manos de forma exagerada, como si estuviera dirigiendo una orquesta",
        "Se quita y pone el sombrero constantemente",
        "Mira hacia el cielo o el techo buscando inspiración",

        // --- Estados de Ánimo Visuales ---
        "Parece al borde del llanto, con los ojos siempre vidriosos",
        "Tiene una sonrisa de suficiencia grabada en la cara",
        "Se muestra distraído, mirando moscas o cosas que nadie más ve",
        "Actúa con una urgencia extrema, como si llegara tarde a algo",
        "Parece que está a punto de quedarse dormido en cualquier momento",
        "Se muestra sospechoso, cubriéndose la boca para que no le lean los labios",
        "Tiene un aire de superioridad, mirando a todos hacia abajo",
        "Está visiblemente asqueado por el entorno o por los jugadores",
        "Muestra una calma inquietante mientras ocurre un caos alrededor",
        "Se ríe entre dientes de sus propios pensamientos",

        // --- Combinaciones de "Efecto" ---
        "Fuma, mira al horizonte y evita responder directamente",
        "Bebe, asiente con la cabeza y tamborilea la mesa",
        "Limpia un objeto, evita el contacto visual y susurra",
        "Se rasca el cuello, parpadea mucho y habla rápido",
        "Postura rígida, manos tras la espalda y mirada fija",
        "Relajado, come frutos secos y sonríe con suficiencia",
        "Se ajusta la ropa, se frota las manos y mira el techo",
        "Muerde sus uñas, mira por encima del hombro y tartamudea"
    ],

fisico: [
        // --- Rostro y Cabeza (70) ---
        "Cicatriz vertical que cruza el ojo izquierdo", "Nariz rota y mal curada en forma de S", "Diente frontal de oro tallado con una runa", "Falta de una oreja (cubierta por el pelo)", "Pecas tan densas que parecen manchas", "Barba trenzada con pequeñas cuentas de hueso", "Cejas tan pobladas que ocultan sus ojos", "Ojos de colores distintos (heterocromía)", "Mandíbula inferior prominente con colmillos salientes", "Labio leporino parcialmente oculto",
        "Tatuaje de una lágrima bajo el ojo derecho", "Piel quemada por el sol y muy agrietada", "Mejillas hundidas y aspecto cadavérico", "Doble mentón muy pronunciado", "Cabeza completamente rapada y pulida", "Largas patillas que llegan hasta la mandíbula", "Cara picada por la viruela o cicatrices de acné", "Lleva un monóculo de cristal ahumado", "Ojos saltones que parecen siempre sorprendidos", "Nariz extremadamente puntiaguda y roja",
        "Cicatriz de quemadura en todo un lado de la cara", "Pelo de un color antinatural (azul, rosa, verde)", "Usa un parche de cuero con un diseño de calavera", "Tiene un tercer ojo tatuado en la frente", "Pestañas blancas como la nieve", "Orejas inusualmente grandes y puntiagudas", "Dientes afilados en punta (estilo tiburón)", "Siempre tiene una brizna de paja en la boca", "Usa una red para el pelo con perlas falsas", "Tiene la cara pintada con ceniza blanca",
        "Cicatriz circular en la frente (marca de una copa)", "Pómulos muy altos y afilados como cuchillas", "Lengua bífida que asoma al hablar", "Sufre de un tic constante en el párpado izquierdo", "Tiene el rostro siempre manchado de hollín", "Lleva piercings de hueso en las cejas", "Piel pálida, casi translúcida, se ven las venas", "Cara redonda y sonrosada como una manzana", "Lleva maquillaje de teatro mal aplicado", "Cicatrices de garras en la mejilla",
        "Barba circular perfectamente recortada", "Tiene una expresión de enfado permanente", "Ojos entrecerrados como si siempre hubiera mucha luz", "Frente muy alta y despejada", "Piel oliva con un brillo aceitoso", "Nariz achatada como la de un boxeador", "Lleva una máscara de cuero que solo cubre la nariz", "Dientes negros por el consumo de alguna raíz", "Tiene un lunar grande con un pelo largo", "Cejas depiladas y dibujadas con carbón",
        "Rostro cubierto de tatuajes tribales", "Lleva un velo fino que oculta su boca", "Pelo recogido en una coleta extremadamente tirante", "Grandes patillas que se unen al bigote", "Usa una dentadura postiza de madera", "Ojos inyectados en sangre por falta de sueño", "Lleva una pequeña joya incrustada en un diente", "Tiene restos de comida siempre en la barba", "Piel muy pecosa en la zona de la nariz", "Usa pendientes que son garras de ave",
        "Cicatriz de un corte de oreja a oreja en el cuello", "Pelo canoso solo en las sienes", "Tiene una mirada que parece ver a través de ti", "Lleva una venda limpia rodeando su cabeza", "Rostro muy asimétrico", "Nariz con un piercing de aro pesado", "Tiene marcas de ventosas en el cuello", "Usa pintura de guerra azul desvaída", "Pelo enmarañado con nidos de pájaro pequeños", "Siempre tiene los labios agrietados y sangrantes",

        // --- Cuerpo y Complexión (80) ---
        "Extremadamente alto y delgado (estilo palo)", "Bajo, ancho y con hombros como un buey", "Le falta el brazo derecho desde el codo", "Camina con una cojera marcada en la pierna izquierda", "Tiene una joroba pronunciada", "Manos desproporcionadamente grandes", "Cuerpo cubierto de vello corporal muy espeso", "Postura encorvada como si cargara un peso invisible", "Tiene seis dedos en la mano derecha", "Piel cubierta de escamas secas en los brazos",
        "Musculatura definida como la de un atleta", "Barriga cervecera que tensa los botones de la ropa", "Cicatriz de un hachazo en el pecho", "Lleva un brazo mecánico (o de madera) rústico", "Tatuaje de un mapa en toda la espalda", "Cuello muy corto, parece que no tiene", "Cintura muy estrecha y hombros anchos", "Cuerpo lleno de hematomas recientes", "Piernas arqueadas como las de un jinete", "Manos temblorosas que no puede detener",
        "Usa una faja de cuero para sostener su espalda", "Tiene una marca de nacimiento con forma de dragón", "Piel bronceada con marcas de armadura", "Lleva una cadena pesada atada a la cintura", "Cuerpo muy ágil, se mueve como un gato", "Tiene los nudillos callosos y deformados", "Hombros caídos y aspecto de cansancio crónico", "Lleva un collar de orejas secas", "Piel muy suave, claramente nunca ha trabajado físicamente", "Tiene cicatrices de latigazos en la espalda",
        "Falta de varios dedos en los pies", "Pecho tatuado con un sol radiante", "Cuerpo muy peludo, incluso en los hombros", "Lleva un grillete roto en el tobillo", "Complexión frágil, parece que se romperá", "Tiene una fuerza física evidente al dar la mano", "Se mueve de forma muy rígida, casi mecánica", "Lleva una mochila que parece pesar más que él", "Piel cubierta de manchas de nacimiento", "Tiene un hombro más alto que el otro",
        "Usa una prótesis de pierna de hierro", "Tatuajes rúnicos que brillan en la oscuridad", "Cuerpo lleno de perforaciones de flechas antiguas", "Manos siempre manchadas de tinta o pintura", "Cuerpo con aroma a flores frescas", "Tiene una quemadura en forma de mano en el brazo", "Lleva un cinturón con veinte bolsillos pequeños", "Viste con capas de ropa que lo hacen parecer más grande", "Tiene un andar saltarín", "Se mueve sin hacer el más mínimo ruido",
        "Cuerpo sudoroso incluso en invierno", "Tiene marcas de garras en los antebrazos", "Lleva una serpiente pequeña tatuada que rodea su cuello", "Falta de un pulgar", "Usa guantes de seda constantes para ocultar algo", "Tiene una postura militar perfecta", "Cuerpo con cicatrices quirúrgicas extrañas", "Lleva una gema incrustada en el ombligo", "Piel con textura de cuero viejo", "Usa una capa hecha de pieles de diferentes animales",
        "Complexión de alguien que ha pasado hambre mucho tiempo", "Tiene un tatuaje de su propio nombre en el brazo", "Lleva una llave colgada del pecho con una cadena de oro", "Cuerpo que parece emitir un ligero calor", "Tiene las uñas pintadas de negro", "Usa un corsé metálico por debajo de la ropa", "Cuerpo con marcas de congelación en las manos", "Lleva una red de pesca como parte de su vestimenta", "Tiene una cola corta (si la especie no la tiene)", "Usa un armazón de madera para corregir su postura",
        "Cuerpo que huele a azufre y humo", "Tiene un tatuaje de una flecha que señala a su cabeza", "Lleva una bolsa de sal atada a la rodilla", "Cuerpo muy flexible, casi contorsionista", "Tiene una marca de quemadura de un rayo", "Lleva un escudo pequeño atado al antebrazo", "Piel cubierta de purpurina o polvo dorado", "Tiene un tic que le hace encoger los hombros", "Usa una máscara de gas rústica colgada al cuello", "Cuerpo que parece vibrar levemente",

        
        // --- Olores y Detalles Finales (75) ---
        "Huele intensamente a canela y clavo", "Huele a perro mojado y barro", "Huele a flores muertas (como de funeral)", "Huele a hierro oxidado y sangre", "Huele a pan recién horneado", "Huele a alcantarilla y humedad", "Huele a humo de pipa muy dulce", "Huele a menta y eucalipto", "Huele a sudor rancio y cuero", "Huele a perfume de rosas abrumador",
        "Huele a mar y salitre", "Huele a incienso de templo antiguo", "Huele a establo y estiércol", "Huele a alcohol fuerte y barato", "Huele a pólvora y azufre", "Huele a madera recién cortada", "Huele a pescado podrido", "Huele a miel y cera de abeja", "Huele a vinagre y productos de limpieza", "Huele a humedad de sótano",
        "Siempre está rodeado de moscas", "Tiene una temperatura corporal muy fría al tacto", "Sus pupilas son rectangulares (como de cabra)", "Tiene las palmas de las manos cubiertas de vello", "Sus uñas cambian de color según su humor", "No tiene ombligo", "Su sombra parece moverse con un segundo de retraso", "Emite un ligero zumbido cuando está nervioso", "Tiene la sangre de color azul brillante", "Sus huellas dactilares son espirales perfectas",
        "Su piel brilla ligeramente bajo la luz de la luna", "Tiene dos filas de dientes", "Sus orejas se mueven cuando escucha un ruido", "No parpadea nunca mientras habla", "Su voz suena como si dos personas hablaran a la vez", "Tiene un pulso muy lento (10 latidos por minuto)", "Sus lágrimas son negras como la tinta", "Su sudor huele a vainilla", "Tiene una marca de quemadura que parece un mapa astral", "Sus rodillas crujen ruidosamente al caminar",
        "Tiene un tatuaje que cambia de lugar cada día", "Sus ojos brillan con una luz tenue en la oscuridad", "Su aliento siempre es gélido, incluso en verano", "Tiene una pequeña cola de conejo", "Sus dedos son inusualmente largos y flexibles", "Tiene una marca de nacimiento en forma de calavera", "Su piel es áspera como el papel de lija", "Tiene una voz que parece venir de detrás de ti", "Su pelo crece unos centímetros durante la conversación", "Tiene un olor a ozono (como antes de una tormenta)",
        "Su risa suena como cristales rompiéndose", "Tiene una cicatriz que brilla cuando hay magia cerca", "Sus pies dejan huellas de ceniza", "Tiene un lunar que parece un ojo pequeño", "Su piel tiene un ligero tono azulado", "Tiene una marca de mordisco de algo muy grande", "Sus manos siempre están calientes como brasas", "Tiene una expresión de absoluta paz", "Su mirada parece hipnótica", "Tiene un mechón de pelo que nunca se queda quieto",
        "Sus ojos son completamente negros, sin blanco", "Tiene una pequeña cicatriz en forma de cruz en la lengua", "Su piel huele a papel viejo y pergamino", "Tiene una marca de quemadura de una corona", "Sus uñas son de metal (o parecen serlo)", "Tiene una voz que te hace querer confiar en él", "Su presencia hace que los animales se pongan nerviosos", "Tiene un tatuaje de un laberinto en la palma de la mano", "Su sombra es más grande de lo que debería ser", "Tiene una marca de nacimiento en forma de estrella",
        "Su piel tiene un brillo metálico", "Tiene una cicatriz de una flecha en el cuello", "Su mirada parece leer tus secretos", "Tiene un olor a tierra mojada", "Su presencia es extrañamente reconfortante"
    ],


ropas_extra: {
        pobre:[
            "Viste harapos que alguna vez fueron seda cara",
            "Lleva una capa hecha de retazos de banderas",
            "Usa botas que le quedan tres tallas grandes",
            "Ropa llena de parches de cuero de colores",
            "Lleva un cinturón hecho de cuerdas de cáñamo",
            "Usa un delantal cubierto de sangre seca",
            "Ropa impregnada de un fuerte olor a perfume barato",
            "Viste con un uniforme militar descolorido",
            "Ropa manchada de vino y comida",
            "Lleva una bufanda de lana larguísima (3 metros)",
            "Lleva una armadura oxidada que chirría",
            "Viste con ropa de cazador llena de hojas y barro",
            "Viste con ropa de marinero muy desgastada",
            "Viste con ropa hecha de sacos de patatas",
            "Viste con ropa de monje, pero lleva armas",
            "Usa un delantal de herrero con marcas de quemaduras",
            "Viste con ropa que parece hecha de algas secas",
            "Lleva una capa roja con el borde deshilachado",
            "Viste con ropa que le queda muy pequeña",
            "Lleva una túnica gris sin ninguna marca",
            "Usa una túnica de lana basta y picante",
            "Viste con ropa de trabajador portuario",
            "Viste con ropa de cuero crudo"
        ],
        media: [
            "Viste completamente de un solo color (ej. amarillo)",
            "Usa una túnica con símbolos religiosos prohibidos",
            "Viste con ropa de una cultura extranjera",
            "Lleva una armadura de cuero tachonada con monedas",
            "Lleva una capucha que siempre oculta sus ojos",
            "Usa guantes de cuero sin dedos",
            "Lleva un manto de plumas de cuervo",
            "Usa un sombrero de ala ancha con campanas colgando",
            "Usa una túnica de lino blanco inmaculado",
            "Usa un kilt de cuadros de un clan desconocido",
            "Lleva una capa que brilla como el aceite",
            "Lleva una túnica con cientos de bolsillos",
            "Usa un sombrero alto de copa aplastado",
            "Usa un cinturón con hebilla de calavera de dragón",
            "Lleva una capa de viaje con capucha de oso",
            "Viste con ropa de colores chillones y opuestos",
            "Usa botas de piel de serpiente",
            "Viste con ropa de luto riguroso",
            "Lleva una armadura de láminas de madera tratada",
            "Viste con ropa de montar impecable",
            "Usa un sombrero de paja con flores secas",
            "Usa un cinturón ancho con cuatro hebillas",
            "Usa botas con espuelas que no sirven para nada",
            "Viste con ropa de explorador llena de mapas cosidos",
            "Usa un sombrero de cuero con gafas de protección",
            "Viste con ropa de gala con manchas de barro",
            "Viste con ropa de entrenamiento de lucha",
            "Usa un manto de oración",
            "Lleva una túnica con un gran sol bordado",
            "Viste con ropa de estilo náutico",
            "Usa un sombrero con forma de barco"
        ],

        rica: [
            "Lleva un sombrero con una pluma de fénix",
            "Viste con elegancia aristocrática, pero sin zapatos",
            "Usa una túnica transparente sobre ropa interior de seda",
            "Lleva un cinturón con muchas herramientas de relojero",
            "Viste con pieles de lobo aún con cabeza",
            "Usa un peto de bronce pulido como un espejo",
            "Lleva una estola de piel de armiño",
            "Lleva un abrigo de piel que le llega a los tobillos",
            "Viste con ropa de gala llena de agujeros de polilla",
            "Usa una túnica con inscripciones mágicas bordadas",
            "Lleva un jubón de terciopelo rojo sangre",
            "Viste con ropa de cuero con remaches de plata",
            "Usa un sombrero de bufón sin cascabeles",
            "Lleva una capa corta de oficial de caballería",
            "Lleva una túnica con flecos de oro",
            "Usa un abrigo con cuello de plumas de pavo real",
            "Lleva una túnica de seda con dibujos de nubes",
            "Lleva una capa de piel de tigre",
            "Lleva una capa de seda azul noche"
        ]
    },

ropas: {
        pobre: [
            "Túnica de lino basto con remiendos de cuero en los codos", "Harapos sucios que alguna vez fueron de color gris", "Pantalones de lana ruda atados con una cuerda de cáñamo", "Delantal de cuero manchado de grasa y hollín", "Poncho de lana de oveja, picante y maloliente", 
            "Camisa descolorida por el sol con agujeros de polilla", "Ropas de trabajo manchadas de barro seco y paja", "Viste solo un taparrabos de piel y una capa de arpillera", "Chaleco de piel de conejo desgastado", "Sayo de tela de saco con aberturas para los brazos",
            "Pantalones bombachos remendados con telas de distintos colores", "Túnica de monje mendicante, raída en los bordes", "Ropa de marinero endurecida por la sal y el sudor", "Vestido de sirvienta con el dobladillo deshilachado", "Manto de viaje con costuras abiertas y manchas de grasa",
            "Camisola de dormir usada como ropa de calle", "Peto de cuero agrietado por falta de aceite", "Ropa de minero cubierta de polvo de carbón", "Falda de lona pesada con bolsillos descosidos", "Capa corta hecha con retales de mantas viejas",
            "Botas desparejadas atadas con tiras de tela", "Calzones de lino que le quedan demasiado grandes", "Túnica con manchas de tinte que no se quitan", "Ropa de pastor con restos de lana pegada", "Jubón de tela barata con botones de madera faltantes"
        ],
        media: [
            "Jubón de cuero bien curtido con hebillas de bronce", "Vestido de algodón con bordados sencillos de flores", "Capa de viaje de lana gruesa con un broche de hierro", "Pantalones de montar reforzados y botas de cuero limpio", "Túnica de escriba con manchas de tinta solo en los puños",
            "Chaleco de terciopelo desgastado pero limpio", "Ropa de mercader: funcional pero con telas de buena calidad", "Hábito clerical con el símbolo sagrado bordado en hilo blanco", "Uniforme de la guardia urbana algo descolorido", "Tabardo de artesano con el sello de su gremio",
            "Vestido de domingo con encaje modesto en el cuello", "Traje de viaje reforzado para el camino", "Capa con capucha forrada de piel de zorro", "Jubón de lana con botones de hueso pulido", "Pantalones de pana y camisa de lino planchada",
            "Ropa de bardo: colorida pero con signos de uso", "Túnica de boticario con muchos bolsillos pequeños", "Delantal de carnicero de cuero grueso y limpio", "Abrigo de paño oscuro con cuello de terciopelo", "Vestido de campesina acomodada con varias enaguas",
            "Sombrero de ala ancha y capa impermeable de aceite", "Botas altas de montar con espuelas de latón", "Guantes de cuero flexible y bufanda de lana", "Cinturón ancho con bolsas de equipo bien organizadas", "Túnica de aprendiz de mago con runas bordadas en el dobladillo",
            "Casaca de lana azul con puños reforzados para el trabajo", "Vestido de lino teñido de ocre con un cinturón de cuero labrado", "Tabardo de sastre con alfileres de plata prendidos en el pecho", "Jubón de pana verde con coderas de gamuza", "Capa de lluvia hecha de lona aceitada con broche de hueso",
            "Protectores de antebrazo de cuero endurecido", "Vestimenta de mercader viajero con múltiples bolsillos interiores", "Corpiño de cuero suave sobre una blusa de algodón blanco", "Pantalones de loneta resistente con botas de media caña", "Chaleco de lana con motivos geométricos bordados",
            "Túnica de templo sencilla pero de tela impecable", "Ropa de boticario con manchas de reactivos químicos coloridos", "Abrigo de paño grueso para el invierno con botones de peltre", "Vestido de ciudadana con una sobrefalda de encaje sencillo", "Jubón de ante con hilos de cobre decorativos",
            "Cinturón de herramientas de cuero bien mantenido", "Sombrero de fieltro con una pequeña pluma de perdiz", "Túnica de bibliotecario con mangas anchas y cómodas", "Ropa de posadero: limpia y con un delantal de algodón", "Capa corta de lana roja con capucha desmontable",
            "Pantalones bombachos de lino y faja de seda barata", "Vestido de maestra con cuello alto y botones de nácar", "Jubón de cazador urbano con refuerzos en los hombros", "Tabardo de mensajero con el escudo de la ciudad", "Chaqueta de lana con botones de madera tallada",
            "Capa de viaje con forro de fieltro para el frío", "Sombrero de ala corta con una cinta de satén", "Camisa de seda de baja calidad con volantes en el pecho", "Vestido de herbolaria con delantal lleno de bolsillos", "Chaqueta de cuero con grabados de hojas",
            "Botas de cuero con hebillas de latón pulido", "Túnica de estudiante universitario con colores académicos", "Ropa de jardinero: práctica pero de tela resistente", "Jubón de terciopelo sintético con bordados de algodón", "Vestido de fiesta sencillo con lazos de colores",
            "Capa de ceremonia menor con bordes de piel sintética", "Pantalones de montar de pana oscura", "Blusa de lino con bordados de hilo negro", "Chaleco de cuero tachonado de forma decorativa", "Sombrero de copa baja con una hebilla de plata",
            "Ropa de músico: llamativa pero algo gastada por los viajes", "Túnica de diácono con estola de lino", "Chaqueta de lana con cuello de pana", "Vestido de lana con cinturón de eslabones de hierro", "Capa de lluvia con hombreras de cuero",
            "Bolsa de costado de cuero grabada con escenas de campo", "Guantes de trabajo de piel de cabra", "Bufanda de seda hilada a mano", "Túnica de esgrima con acolchado ligero", "Delantal de joyero con lupas colgando"
        ],
        rica: [
            "Capa de seda azul noche con bordes de hilo de plata", "Jubón de terciopelo carmesí con botones de perlas", "Vestido de gala con incrustaciones de piedras preciosas pequeñas", "Túnica de seda translúcida sobre capas de lino fino", "Armadura ceremonial de placas grabada con filigrana de oro",
            "Manto de armiño blanco con broche de oro macizo", "Ropa de corte con mangas excesivamente largas y decoradas", "Vestido de seda con un corsé rígido de ballena", "Botas de piel de serpiente exótica con puntas afiladas", "Sombrero ostentoso con plumas de ave del paraíso",
            "Toga de magistrado con franjas púrpura de tinte caro", "Traje de equitación de seda reforzada y cuero de dragón", "Capa tornasolada que cambia de color según la luz", "Guantes de encaje fino y abanico de marfil", "Cinturón de eslabones de plata con un gran rubí en la hebilla",
            "Ropa de moda extranjera con cortes asimétricos", "Túnica de archimago con constelaciones bordadas en mithril", "Manto de plumas de pavo real auténticas", "Vestido de novia con metros de encaje y seda", "Chaleco de brocado de oro con motivos heráldicos",
            "Capa corta de piel de oso blanco del norte", "Calzones de seda con bordados de dragones en hilo de oro", "Coraza de cristal ornamental para desfiles", "Sombrero de ala ancha con una joya colgante", "Túnica de gala con hombreras rígidas bañadas en plata",
            "Capa de piel de pantera de las nieves con broche de diamante", "Jubón de seda tejida con hilos de oro puro", "Vestido de gala con una cola cargada de perlas naturales", "Túnica de gasa estelar con efectos mágicos de luz", "Coraza de plata pulida decorada con relieves épicos",
            "Manto de plumas de fénix que emite un suave brillo", "Gola de encaje arquitectónico almidonado", "Vestido de terciopelo negro con diamantes cosidos", "Botas de cuero de dragón rojo con tacones de obsidiana", "Tocado de oro con forma de sol radiante",
            "Toga de senador con bordados de hilo de platino", "Traje de equitación de piel de unicornio sintética", "Capa aromática que desprende sándalo al caminar", "Guantes de seda de araña con uñas de oro", "Cinturón de mithril con hebilla de ópalo",
            "Ropa de moda asimétrica de los planos exteriores", "Túnica de mago con runas que reaccionan a la temperatura", "Manto de piel de tigre dientes de sable", "Vestido de novia de seda de sirena iridiscente", "Chaleco de brocado con escenas históricas",
            "Capa de lana de cordero celestial, blanca y etérea", "Pantalones de seda con hilos de rubí", "Corsé de placas de nácar pulido", "Sombrero de ala ancha con pluma de grifo real", "Túnica de gala con mangas flotantes",
            "Abrigo de zorro ártico con forro de seda púrpura", "Traje de duelo de seda con láminas de acero ocultas", "Vestido de baile que suena como campanas de cristal", "Capa de oficial real con bordados en relieve", "Túnica de embajador de las naciones aliadas",
            "Sandalias de cuero de basilisco y esmeraldas", "Máscara de oro que cubre solo la mitad del rostro", "Vestido hecho de pétalos preservados mágicamente", "Chaqueta de terciopelo con hombreras de plumas de avestruz", "Capa de viaje de seda reforzada para nobles",
            "Sombrero con reloj de sol de oro integrado", "Ropa de dormir de seda con hilos de plata", "Túnica sacerdotal de alto rango con gemas sacras", "Manto de ceremonia de escamas de dragón", "Jubón con pechera de perlas incrustadas",
            "Vestido de encaje negro sobre seda carmesí", "Guantes de seda con anillos decorativos cosidos", "Botas de ante con bordados de escenas de caza reales", "Capa de terciopelo con capucha de seda arcoíris", "Túnica de explorador de lujo en cuero de manticora",
            "Collar que sostiene una gema del tamaño de un huevo de ave", "Pantalones de montar de cuero exótico", "Chaqueta con botones de cristal que contienen fuego fatuo", "Manto de invierno de piel de oso polar blanco", "Traje de gala con capa levitante"
        ],
        aventurero: [
            "Armadura de cuero tachonado llena de muescas de combate", "Capa de camuflaje con hojas y ramas cosidas", "Ropa de cuero ajustada con fundas para múltiples dagas", "Manto de viaje raído por el viento de las montañas", "Túnica reforzada con mallas metálicas ocultas",
            "Ropa de explorador con refuerzos de piel en las rodillas", "Uniforme de mercenario con manchas de sangre vieja", "Capa impermeable de piel de monstruo", "Botas de suela gruesa preparadas para el barro y la roca", "Vestimenta de monje guerrero, simple pero muy resistente",
            "Cinturón cruzado con viales de pociones vacíos", "Pantalones de cuero con parches de cota de malla", "Túnica oscura diseñada para fundirse con las sombras", "Ropa de marinero de alta mar con protecciones térmicas", "Tabardo de caballero andante con escudo desgastado",
            "Capa élfica que imita las texturas del entorno", "Ropa de bárbaro hecha de pieles brutas y trofeos óseos", "Túnica de clérigo de guerra con refuerzos metálicos", "Vestimenta de pícaro con docenas de bolsillos ocultos", "Poncho de cuero endurecido contra proyectiles",
            "Traje de explorador de mazmorras con ganchos y cuerdas", "Ropa de cazador con olor a almizcle de bosque", "Túnica de hechicero con quemaduras de conjuros", "Armadura acolchada bajo una capa de viaje simple", "Botas de explorador veterano reforzadas"
        ]
    },

    wants: [
        "Llegar a casa lo antes posible para ver a su familia", "Conseguir suficiente dinero para pagar una deuda de juego", "Encontrar a alguien que le ayude a cargar un fardo pesado", "Vengar una afrenta menor que recibió esta mañana", "Impresionar a un superior para conseguir un ascenso",
        "Conseguir una cita con alguien que trabaja en la taberna", "Evitar a toda costa que la guardia le haga preguntas", "Vender un objeto 'mágico' que sabe que es falso", "Encontrar a su mascota desaparecida (un hurón o una rata)", "Aprender un nuevo chiste para contarlo en la cena",
        "Que alguien escuche su larguísima historia personal", "Encontrar una cura para un dolor de muela persistente", "Conseguir que los jugadores le compren una bebida", "Saber quién es el forastero que acaba de llegar al pueblo", "Recuperar una carta de amor que le robaron",
        "Demostrar que es el mejor en su oficio", "Hacer que alguien se ría de sus desgracias", "Conseguir un autógrafo de un héroe famoso", "Que los jugadores le den una moneda por un 'secreto' inútil", "Encontrar un lugar seguro para pasar la noche",
        "Apostar en cualquier cosa que los jugadores estén haciendo", "Deshacerse de un objeto que cree que da mala suerte", "Que alguien le ayude a leer un documento oficial", "Descubrir si su pareja le está siendo infiel", "Conseguir suministros baratos para su negocio",
        "Entrar en una fiesta privada a la que no fue invitado", "Hacer que la guardia arreste a su rival comercial", "Comprar un regalo para el cumpleaños de su hijo", "Averiguar qué hay dentro de un paquete sospechoso", "Simplemente quiere que alguien le trate con respeto",
        "Conseguir una receta secreta de un pueblo vecino", "Probar que los dragones no existen (o que sí)", "Hacer que los jugadores lleven un mensaje a la ciudad vecina", "Ganar un concurso de comida o bebida local", "Recuperar una herramienta que empeñó por necesidad",
        "Que alguien le ayude a mover un carro atascado", "Encontrar una excusa para no ir a trabajar hoy", "Saber la hora exacta cada cinco minutos", "Que los jugadores le hablen de sus tierras lejanas", "Conseguir un mapa 'del tesoro' que vio en un mercadillo",
        "Asegurarse de que nadie toque sus pertenencias", "Encontrar un ingrediente raro para una cena especial", "Hacerse pasar por alguien más importante", "Que alguien le confirme que su ropa está a la moda", "Evitar un encuentro con un acreedor que está cerca",
        "Encontrar a un experto que valore una joya", "Que alguien le explique qué es la magia", "Conseguir un trabajo como guardaespaldas temporal", "Convencer a alguien de que se una a su culto (un poco ridículo)", "Que le devuelvan un favor que hizo hace años",
        "Hacer que los jugadores prueben su nuevo invento", "Saber si es verdad que el Rey está enfermo", "Limpiar su buen nombre tras un malentendido", "Que alguien le ayude a bajar un gato de un tejado", "Encontrar a su hermano gemelo perdido",
        "Conseguir que alguien le traduzca una palabra en elfo", "Apostar su última moneda en una pelea de taberna", "Que los jugadores le cuenten una historia de miedo", "Encontrar un remedio para la calvicie", "Ser recordado como un héroe, aunque sea por un día",
        "Conseguir una invitación para el baile de máscaras", "Averiguar quién robó su ropa mientras se bañaba", "Hacer un trato comercial con los jugadores", "Que alguien le sostenga una antorcha un momento", "Encontrar una piedra de la suerte (o un guijarro común)",
        "Saber dónde se esconde el mercado negro", "Conseguir un tinte para el pelo que no sea verde", "Que alguien le ayude a escribir una elegía", "Encontrar una excusa para beber gratis", "Descubrir el punto débil de su jefe",
        "Convencer a los jugadores de que compren su burro viejo", "Hacer que alguien le lleve en brazos un tramo", "Encontrar un zapato que perdió", "Que alguien le defienda de un matón", "Saber si los jugadores son reales o ilusiones",
        "Conseguir un permiso de caza ilegal", "Hacer que alguien le lea el futuro", "Encontrar una fuente de agua pura", "Que los jugadores se queden a cenar en su casa", "Conseguir una confesión de un ladrón",
        "Vender su alma al mejor postor (literalmente)", "Hacer que el bardo toque su canción favorita", "Que alguien le ayude a esconder un cuerpo (animal, jura)", "Encontrar una moneda que se le cayó en la alcantarilla", "Conseguir que los jugadores le adopten",
        "Averiguar qué significa un sueño recurrente", "Hacer que alguien le compre un par de botas nuevas", "Encontrar a alguien que sepa de heráldica", "Que los jugadores le ayuden a practicar su esgrima", "Conseguir un ingrediente para un veneno débil",
        "Saber por qué todo el mundo le mira raro", "Hacer que alguien le sujete el sombrero", "Encontrar una aguja en un pajar (literalmente)", "Que los jugadores le firmen un documento de 'buen ciudadano'", "Conseguir una poción de amor verdadera",
        "Averiguar si los elfos realmente no duermen", "Hacer que alguien le limpie las botas", "Encontrar un tesoro familiar en una tumba", "Que los jugadores le enseñen un truco de magia", "Conseguir el perdón de un viejo enemigo"
    ],

    // --- 200 SECRETOS (TWISTS) ---
    twists: [
        "Es un espía de una facción enemiga", "En realidad es un hombre lobo (pero no lo sabe)", "Lleva un objeto maldito que le obliga a mentir", "Es un noble fugitivo disfrazado de plebeyo", "No sabe leer, pero finge hacerlo constantemente",
        "Es un Doppelganger novato que olvida detalles", "En su tiempo libre es un asesino a sueldo famoso", "Está bajo el efecto de un hechizo de 'Modificar Memoria'", "Lleva una bolsa con 500 piezas de oro robadas", "Es un fantasma que no sabe que ha muerto",
        "Tiene una deuda de sangre con un demonio", "En realidad es dos medianos uno encima del otro", "Es el verdadero heredero al trono local", "Ha sido enviado para asesinar a uno de los jugadores", "Sabe dónde está enterrado el tesoro de la ciudad",
        "Es un fanático religioso de un dios prohibido", "Lleva un mapa tatuado en el cuero cabelludo", "Su sombra se mueve de forma independiente a veces", "En realidad es un dragón joven transformado", "Está poseído por el espíritu de un bardo bromista",
        "Ha envenenado la comida de la taberna (por error)", "Es un viajero del tiempo de una era futura", "Trabaja para el villano principal de la campaña", "En realidad es un criminal buscado en tres reinos", "Ha hecho un pacto para ser inmortal, pero solo si no parpadea",
        "Es un experto en venenos y lleva varios encima", "Su ropa es en realidad un mímico domesticado", "Está buscando a los jugadores para pedirles matrimonio", "Es el autor de todos los libros de chismes de la ciudad", "Tiene una maldición que hace que los animales le hablen",
        "Es un veterano de una guerra que nunca ocurrió", "Lleva un huevo de criatura exótica en su mochila", "En realidad es un mago de nivel 20 que ha perdido la memoria", "Su familia fue asesinada por alguien que se parece a un jugador", "Es un informante de la guardia urbana",
        "Está infectado con una enfermedad mágica contagiosa", "En realidad es un títere controlado por hilos invisibles", "Es el líder de un gremio de ladrones local", "Lleva un mensaje secreto escrito en su piel con tinta invisible", "Es un refugiado de otro plano de existencia",
        "Su 'mascota' es en realidad su patrón de brujo", "Tiene miedo a la magia y entra en pánico si la ve", "Es un experto en cerraduras y trampas", "Ha robado el cáliz sagrado del templo esta mañana", "En realidad es un crítico de tabernas encubierto",
        "Sufre de amnesia y cree que los jugadores son sus hijos", "Lleva un anillo que le permite escuchar pensamientos cercanos", "Es un espía de los jugadores enviado por un aliado", "Su familia es una estirpe de vampiros (él aún no lo es)", "Tiene un gemelo malvado que está cerca",
        "Lleva un objeto que es la llave de una prisión antigua", "Es un erudito que busca un sacrificio humano", "En realidad es un bardo famoso cansado de la fama", "Tiene una marca de nacimiento que indica que es 'el elegido'", "Es un agente doble (o triple)",
        "Su voz es el resultado de un hechizo de silencio fallido", "Lleva una carta que prueba una conspiración real", "En realidad es un constructo mecánico muy avanzado", "Está muerto por dentro (literalmente, es un no-muerto inteligente)", "Es un coleccionista de ojos de diferentes especies",
        "Cree que el mundo es una simulación (o un juego de dados)", "Es un desertor de una legión infernal", "Tiene una pequeña hada atrapada en un frasco", "Es un experto en la lengua de los dragones", "Su familia le vendió a una bruja cuando era niño",
        "Lleva un arma legendaria pero cree que es una imitación", "Es un artista que pinta el futuro", "Tiene un pacto con un ser del plano de los sueños", "En realidad es el alcalde de la ciudad disfrazado", "Sabe cómo entrar en la tesorería real",
        "Es un caníbal rehabilitado (o no)", "Lleva un colgante que es un filacteria de un lich", "Es un marinero que nunca ha visto el mar", "Tiene una fobia irracional a los elfos (o enanos)", "Es un polizón de un barco volador",
        "Su aliento puede matar moscas al instante", "Lleva una joya que es el corazón de un elemental", "Es un monje que ha roto su voto de silencio hoy", "En realidad es un cazarrecompensas buscando a los jugadores", "Es un mensajero que lleva un mensaje que él mismo alteró",
        "Sabe el verdadero nombre de un demonio poderoso", "Es un adicto a una poción rara", "Tiene una colección de dientes de aventureros", "Es un noble que fue convertido en plebeyo por un deseo", "Lleva un secreto que destruiría la iglesia local",
        "Es un experto en falsificar monedas de platino", "Su sombra tiene cuernos, aunque él no", "Es un antiguo héroe que fue resucitado mal", "Lleva un diario de todas las personas que ha matado", "Es un guardián de una entrada al Inframundo",
        "Tiene una lengua de plata (literalmente, de metal)", "Es un infiltrado de una sociedad secreta de magos", "Sabe quién es el traidor en el grupo de los jugadores", "Lleva una maldición que atrae los rayos", "Es un cocinero que usa ingredientes 'humanoides'",
        "En realidad es un avatar de un dios menor aburrido", "Es un fanático de los jugadores y les sigue a todas partes", "Lleva un mapa del tesoro tatuado en su lengua", "Es un ex-cultista que huye de sus antiguos hermanos", "Sabe cómo detener el fin del mundo (pero es muy caro)"
    ]
};
